module.exports = Object.freeze({
	PDP_REST_HOST: "nextlabs.cloudaz.host",
	PDP_REST_PORT: "nextlabs.cloudaz.port",
	PDP_REST_RESOURCE_PATH: "nextlabs.cloudaz.resource_path",
	PDP_REST_HTTPS: "nextlabs.cloudaz.https",
	PDP_REST_IGNORE_HTTPS_CERTIFICATE: "nextlabs.cloudaz.ignore_https_certificate",
	PDP_REST_AUTH_TYPE: "nextlabs.cloudaz.auth_type",
	PDP_REST_CAS_AUTH_USERNAME: "nextlabs.cloudaz.cas_auth.username",
	PDP_REST_CAS_AUTH_PASSWORD: "nextlabs.cloudaz.cas_auth.password",
	PDP_REST_OAUTH2_SERVER: "nextlabs.cloudaz.oauth2.server",
	PDP_REST_OAUTH2_PORT: "nextlabs.cloudaz.oauth2.port",
	PDP_REST_OAUTH2_HTTPS: "nextlabs.cloudaz.oauth2.https",
	PDP_REST_OAUTH2_TOKEN_ENDPOINT_PATH: "nextlabs.cloudaz.oauth2.token_endpoint_path",
	PDP_REST_OAUTH2_TOKEN_GRANT_TYPE: "nextlabs.cloudaz.oauth2.grant_type",
	PDP_REST_OAUTH2_TOKEN_EXPIRES_IN: "nextlabs.cloudaz.oauth2.token_expires_in",
	// for grant_type:= password
	PDP_REST_OAUTH2_USERNAME: "nextlabs.cloudaz.oauth2.username",
	PDP_REST_OAUTH2_PASSWORD: "nextlabs.cloudaz.oauth2.password",
	// for grant_type:= client_credentials
	PDP_REST_OAUTH2_CLIENT_ID: "nextlabs.cloudaz.oauth2.client_id",
	PDP_REST_OAUTH2_CLIENT_SECRET: "nextlabs.cloudaz.oauth2.client_secret",
	DEFAULT_HOST:"localhost",
	DEFAULT_HTTP_PORT: 58080,
	DEFAULT_HTTPS_PORT: 443,
	DEFAULT_RES_PATH:"/dpc/authorization/pdp",
	NONE_AUTH_TYPE:"NONE",
	CAS_AUTH_TYPE:"CAS_AUTH",
	OAUTH2_AUTH_TYPE:"OAUTH2",
	OAUTH2_GRANT_TYPE_CLIENT_CREDENTIALS: "client_credentials",
	OAUTH2_GRANT_TYPE_PASSWORD: "password",
	CAS_TICKET_PATH:"/cas/v1/tickets",
	DEFAULT_PDP_REST_OAUTH2_GRANT_TYPE: "client_credentials",
	DEFAULT_PDP_REST_OAUTH2_HTTPS: true,
	DEFAULT_PDP_REST_OAUTH2_PORT: 443,
	DEFAULT_PDP_REST_OAUTH2_TOKEN_ENDPOINT_PATH: "/oauth/token",
	DEFAULT_PDP_REST_OAUTH2_TOKEN_EXPIRES_IN: 3600,
	JSON_REQUEST:"json",
	XML_REQUEST:"xml",
	LOCAL_HOST:"localhost",
	API_VERSION: "1.0",
	API_DATA_TYPE_JSON: "json",
	API_SERVICE: "EVAL",
	DEFAULT_INET_ADDRESS: "2130706433",
});
