"use strict";

var XACML = require("./XACML");
var XACML1 = require("./XACML1");
var XACML2 = require("./XACML2");
var Utils = require("../Utils");

module.exports = Object.freeze(new function() {
    /*
     * Namespace and Schema constants
     */
    this.SCHEMA_LOCATION = "urn:oasis:names:tc:xacml:3.0:core:schema:wd-17 http://docs.oasis-open.org/xacml/3.0/xacml-core-v3-schema-wd-17.xsd";
    this.XMLNS = "urn:oasis:names:tc:xacml:3.0:core:schema:wd-17";
    this.XMLNS_XSI = "http://www.w3.org/2001/XMLSchema-instance";

    /*
     * 10.2.1 Schema elements DOM Elements and Attributes TODO: Copy any of these to the XACML1 and XACML2
     * constants object if they are available there, and then reference them here
     */
    this.ELEMENT_ADVICE = "Advice";
    this.ELEMENT_ADVICEEXPRESSION = "AdviceExpression";
    this.ELEMENT_ADVICEEXPRESSIONS = "AdviceExpressions";
    this.ELEMENT_ALLOF = "AllOf";
    this.ELEMENT_ANYOF = "AnyOf";
    this.ELEMENT_APPLY = "Apply";
    this.ELEMENT_ASSOCIATEDADVICE = "AssociatedAdvice";
    this.ELEMENT_ATTRIBUTE = "Attribute";
    this.ELEMENT_ATTRIBUTEASSIGNMENT = "AttributeAssignment";
    this.ELEMENT_ATTRIBUTEASSIGNMENTEXPRESSION = "AttributeAssignmentExpression";
    this.ELEMENT_ATTRIBUTEDESIGNATOR = "AttributeDesignator";
    this.ELEMENT_ATTRIBUTESELECTOR = "AttributeSelector";
    this.ELEMENT_ATTRIBUTESREFERENCE = "AttributesReference";
    this.ELEMENT_ATTRIBUTES = "Attributes";
    this.ELEMENT_ATTRIBUTEVALUE = "AttributeValue";
    this.ELEMENT_CONDITION = "Condition";
    this.ELEMENT_COMBINERPARAMETER = "CombinerParameter";
    this.ELEMENT_COMBINERPARAMETERS = "CombinerParameters";
    this.ELEMENT_CONTENT = "Content";
    this.ELEMENT_DECISION = "Decision";
    this.ELEMENT_DESCRIPTION = "Description";
    this.ELEMENT_EXPRESSION = "Expression";
    this.ELEMENT_FUNCTION = "Function";
    this.ELEMENT_MATCH = "Match";
    this.ELEMENT_MISSINGATTRIBUTEDETAIL = "MissingAttributeDetail";
    this.ELEMENT_MULTIREQUESTS = "MultiRequests";
    this.ELEMENT_OBLIGATION = "Obligation";
    this.ELEMENT_OBLIGATIONEXPRESSION = "ObligationExpression";
    this.ELEMENT_OBLIGATIONEXPRESSIONS = "ObligationExpressions";
    this.ELEMENT_OBLIGATIONS = "Obligations";
    this.ELEMENT_POLICY = "Policy";
    this.ELEMENT_POLICYCOMBINERPARAMETERS = "PolicyCombinerParameters";
    this.ELEMENT_POLICYDEFAULTS = "PolicyDefaults";
    this.ELEMENT_POLICYIDENTIFIERLIST = "PolicyIdentifierList";
    this.ELEMENT_POLICYIDREFERENCE = "PolicyIdReference";
    this.ELEMENT_POLICYISSUER = "PolicyIssuer";
    this.ELEMENT_POLICYSET = "PolicySet";
    this.ELEMENT_POLICYSETCOMBINERPARAMETERS = "PolicySetCombinerParameters";
    this.ELEMENT_POLICYSETDEFAULTS = "PolicySetDefaults";
    this.ELEMENT_POLICYSETIDREFERENCE = "PolicySetIdReference";
    this.ELEMENT_REQUEST = "Request";
    this.ELEMENT_REQUESTDEFAULTS = "RequestDefaults";
    this.ELEMENT_REQUESTREFERENCE = "RequestReference";
    this.ELEMENT_RESPONSE = "Response";
    this.ELEMENT_RESULT = "Result";
    this.ELEMENT_RULE = "Rule";
    this.ELEMENT_RULECOMBINERPARAMETERS = "RuleCombinerParameters";
    this.ELEMENT_STATUS = "Status";
    this.ELEMENT_STATUSCODE = "StatusCode";
    this.ELEMENT_STATUSDETAIL = "StatusDetail";
    this.ELEMENT_STATUSMESSAGE = "StatusMessage";
    this.ELEMENT_TARGET = "Target";
    this.ELEMENT_VARIABLEDEFINITION = "VariableDefinition";
    this.ELEMENT_VARIABLEREFERENCE = "VariableReference";
    this.ELEMENT_XPATHVERSION = "XPathVersion";

    this.ATTRIBUTE_ADVICEID = "AdviceId";
    this.ATTRIBUTE_APPLIESTO = "AppliesTo";
    this.ATTRIBUTE_ATTRIBUTEID = "AttributeId";
    this.ATTRIBUTE_CATEGORY = "Category";
    this.ATTRIBUTE_COMBINEDDECISION = "CombinedDecision";
    this.ATTRIBUTE_CONTEXTSELECTORID = "ContextSelectorId";
    this.ATTRIBUTE_DATATYPE = "DataType";
    this.ATTRIBUTE_EARLIESTVERSION = "EarliestVersion";
    this.ATTRIBUTE_EFFECT = "Effect";
    this.ATTRIBUTE_FULFILLON = "FulfillOn";
    this.ATTRIBUTE_FUNCTIONID = "FunctionId";
    this.ATTRIBUTE_LATESTVERSION = "LatestVersion";
    this.ATTRIBUTE_ID = "id"; // xml:id
    this.ATTRIBUTE_INCLUDEINRESULT = "IncludeInResult";
    this.ATTRIBUTE_ISSUER = "Issuer";
    this.ATTRIBUTE_MATCHID = "MatchId";
    this.ATTRIBUTE_MAXDELEGATIONDEPTH = "MaxDelegationDepth";
    this.ATTRIBUTE_MUSTBEPRESENT = "MustBePresent";
    this.ATTRIBUTE_OBLIGATIONID = "ObligationId";
    this.ATTRIBUTE_PARAMETERNAME = "ParameterName";
    this.ATTRIBUTE_PATH = "Path";
    this.ATTRIBUTE_POLICYCOMBININGALGID = "PolicyCombiningAlgId";
    this.ATTRIBUTE_POLICYID = "PolicyId";
    this.ATTRIBUTE_POLICYIDREF = "PolicyIdRef";
    this.ATTRIBUTE_POLICYSETID = "PolicySetId";
    this.ATTRIBUTE_POLICYSETIDREF = "PolicySetIdRef";
    this.ATTRIBUTE_REFERENCEID = "ReferenceId";
    this.ATTRIBUTE_RETURNPOLICYIDLIST = "ReturnPolicyIdList";
    this.ATTRIBUTE_RULECOMBININGALGID = "RuleCombiningAlgId";
    this.ATTRIBUTE_RULEID = "RuleId";
    this.ATTRIBUTE_RULEIDREF = "RuleIdRef";
    this.ATTRIBUTE_VALUE = "Value";
    this.ATTRIBUTE_VARIABLEID = "VariableId";
    this.ATTRIBUTE_VERSION = "Version";
    this.ATTRIBUTE_XPATHCATEGORY = "XPathCategory";

    /*
     * 10.2.2 Identifier Prefixes
     */
    this.VERSION = "3.0";
    this.ID_XACML = Utils.resolveURI(XACML.ID_XACML, this.VERSION);
    this.ID_CONFORMANCE_TEST = XACML2.ID_CONFORMANCE_TEST;
    this.ID_CONTEXT = XACML2.ID_CONTEXT;
    this.ID_EXAMPLE = XACML2.ID_EXAMPLE;
    this.ID_FUNCTION10 = XACML1.ID_FUNCTION;
    this.ID_FUNCTION20 = XACML2.ID_FUNCTION;
    this.ID_FUNCTION = Utils.resolveURI(this.ID_XACML, XACML.FUNCTION);
    this.ID_POLICY = XACML2.ID_POLICY;
    this.ID_SUBJECT = XACML1.ID_SUBJECT;
    this.ID_RESOURCE = XACML1.ID_RESOURCE;
    this.ID_ACTION = XACML1.ID_ACTION;
    this.ID_ENVIRONMENT = XACML1.ID_ENVIRONMENT;
    this.ID_STATUS = XACML1.ID_STATUS;
    this.ID_ATTRIBUTE_CATEGORY = Utils.resolveURI(this.ID_XACML, "attribute-category");

    /*
     * 10.2.3 Algorithms
     */
    this.ID_RULE_COMBINING_ALGORITHM = Utils.resolveURI(this.ID_XACML, "rule-combining-algorithm");
    this.ID_POLICY_COMBINING_ALGORITHM = Utils.resolveURI(this.ID_XACML, "policy-combining-algorithm");

    this.ID_RULE_DENY_OVERRIDES = Utils.resolveURI(this.ID_RULE_COMBINING_ALGORITHM, XACML1.DENY_OVERRIDES);
    this.ID_POLICY_DENY_OVERRIDES = Utils.resolveURI(this.ID_POLICY_COMBINING_ALGORITHM, XACML1.DENY_OVERRIDES);
    this.ID_RULE_PERMIT_OVERRIDES = Utils.resolveURI(this.ID_RULE_COMBINING_ALGORITHM, XACML1.PERMIT_OVERRIDES);
    this.ID_POLICY_PERMIT_OVERRIDES = Utils.resolveURI(this.ID_POLICY_COMBINING_ALGORITHM, XACML1.PERMIT_OVERRIDES);
    this.ID_RULE_FIRST_APPLICABLE = XACML1.ID_RULE_FIRST_APPLICABLE;
    this.ID_POLICY_FIRST_APPLICABLE = XACML1.ID_POLICY_FIRST_APPLICABLE;
    this.ID_RULE_ONLY_ONE_APPLICABLE = XACML1.ID_RULE_ONLY_ONE_APPLICABLE;
    this.ID_POLICY_ONLY_ONE_APPLICABLE = XACML1.ID_POLICY_ONLY_ONE_APPLICABLE;
    this.ID_RULE_ORDERED_DENY_OVERRIDES = Utils.resolveURI(this.ID_RULE_COMBINING_ALGORITHM, XACML1.ORDERED_DENY_OVERRIDES);
    this.ID_POLICY_ORDERED_DENY_OVERRIDES = Utils.resolveURI(this.ID_POLICY_COMBINING_ALGORITHM, XACML1.ORDERED_DENY_OVERRIDES);
    this.ID_RULE_ORDERED_PERMIT_OVERRIDES = Utils.resolveURI(this.ID_RULE_COMBINING_ALGORITHM, XACML1.ORDERED_PERMIT_OVERRIDES);
    this.ID_POLICY_ORDERED_PERMIT_OVERRIDES = Utils.resolveURI(this.ID_POLICY_COMBINING_ALGORITHM, XACML1.ORDERED_PERMIT_OVERRIDES);
    this.DENY_UNLESS_PERMIT = "deny-unless-permit";
    this.ID_RULE_DENY_UNLESS_PERMIT = Utils.resolveURI(this.ID_RULE_COMBINING_ALGORITHM, this.DENY_UNLESS_PERMIT);
    this.ID_POLICY_DENY_UNLESS_PERMIT = Utils.resolveURI(this.ID_POLICY_COMBINING_ALGORITHM, this.DENY_UNLESS_PERMIT);
    this.PERMIT_UNLESS_DENY = "permit-unless-deny";
    this.ID_RULE_PERMIT_UNLESS_DENY = Utils.resolveURI(this.ID_RULE_COMBINING_ALGORITHM, this.PERMIT_UNLESS_DENY);
    this.ID_POLICY_PERMIT_UNLESS_DENY = Utils.resolveURI(this.ID_POLICY_COMBINING_ALGORITHM, this.PERMIT_UNLESS_DENY);

    this.ID_RULE_LEGACY_DENY_OVERRIDES = XACML1.ID_RULE_DENY_OVERRIDES;
    this.ID_POLICY_LEGACY_DENY_OVERRIDES = XACML1.ID_POLICY_DENY_OVERRIDES;
    this.ID_RULE_LEGACY_PERMIT_OVERRIDES = XACML1.ID_RULE_PERMIT_OVERRIDES;
    this.ID_POLICY_LEGACY_PERMIT_OVERRIDES = XACML1.ID_POLICY_PERMIT_OVERRIDES;
    this.ID_RULE_LEGACY_ORDERED_DENY_OVERRIDES = XACML1.ID_RULE_ORDERED_DENY_OVERRIDES;
    this.ID_POLICY_LEGACY_ORDERED_DENY_OVERRIDES = XACML1.ID_POLICY_ORDERED_DENY_OVERRIDES;
    this.ID_RULE_LEGACY_ORDERED_PERMIT_OVERRIDES = XACML1.ID_RULE_ORDERED_PERMIT_OVERRIDES;
    this.ID_POLICY_LEGACY_ORDERED_PERMIT_OVERRIDES = XACML1.ID_POLICY_ORDERED_PERMIT_OVERRIDES;

    /*
     * 10.2.4 Status Codes
     */
    this.ID_STATUS_MISSING_ATTRIBUTE = XACML1.ID_STATUS_MISSING_ATTRIBUTE;
    this.ID_STATUS_OK = XACML1.ID_STATUS_OK;
    this.ID_STATUS_PROCESSING_ERROR = XACML1.ID_STATUS_PROCESSING_ERROR;
    this.ID_STATUS_SYNTAX_ERROR = XACML1.ID_STATUS_SYNTAX_ERROR;

    /*
     * Section 10.2.5 Attributes
     */
    this.ID_ENVIRONMENT_CURRENT_TIME = XACML1.ID_ENVIRONMENT_CURRENT_TIME;
    this.ID_ENVIRONMENT_CURRENT_DATE = XACML1.ID_ENVIRONMENT_CURRENT_DATE;
    this.ID_ENVIRONMENT_CURRENT_DATETIME = XACML1.ID_ENVIRONMENT_CURRENT_DATETIME;

    /*
     * Section 10.2.6 Identifiers
     */
    this.ID_SUBJECT_AUTHN_LOCALITY = XACML1.ID_SUBJECT_AUTHN_LOCALITY;
    this.ID_SUBJECT_AUTHN_LOCALITY_DNS_NAME = XACML1.ID_SUBJECT_AUTHN_LOCALITY_DNS_NAME;
    this.ID_SUBJECT_AUTHN_LOCALITY_IP_ADDRESS = XACML1.ID_SUBJECT_AUTHN_LOCALITY_IP_ADDRESS;
    this.ID_SUBJECT_AUTHENTICATION_METHOD = XACML1.ID_SUBJECT_AUTHENTICATION_METHOD;
    this.ID_SUBJECT_AUTHENTICATION_TIME = XACML1.ID_SUBJECT_AUTHENTICATION_TIME;
    this.ID_SUBJECT_KEY_INFO = XACML1.ID_SUBJECT_KEY_INFO;
    this.ID_SUBJECT_REQUEST_TIME = XACML1.ID_SUBJECT_REQUEST_TIME;
    this.ID_SUBJECT_SESSION_START_TIME = XACML1.ID_SUBJECT_SESSION_START_TIME;
    this.ID_SUBJECT_SUBJECT_ID = XACML1.ID_SUBJECT_SUBJECT_ID;
    this.ID_SUBJECT_SUBJECT_ID_QUALIFIER = XACML1.ID_SUBJECT_SUBJECT_ID_QUALIFIER;
    this.ID_SUBJECT_CATEGORY_ACCESS_SUBJECT = XACML1.ID_SUBJECT_CATEGORY_ACCESS_SUBJECT;
    this.ID_SUBJECT_CATEGORY_CODEBASE = XACML1.ID_SUBJECT_CATEGORY_CODEBASE;
    this.ID_SUBJECT_CATEGORY_INTERMEDIARY_SUBJECT = XACML1.ID_SUBJECT_CATEGORY_INTERMEDIARY_SUBJECT;
    this.ID_SUBJECT_CATEGORY_RECIPIENT_SUBJECT = XACML1.ID_SUBJECT_CATEGORY_RECIPIENT_SUBJECT;
    this.ID_SUBJECT_CATEGORY_REQUESTING_MACHINE = XACML1.ID_SUBJECT_CATEGORY_REQUESTING_MACHINE;
    this.ID_RESOURCE_RESOURCE_LOCATION = XACML1.ID_RESOURCE_RESOURCE_LOCATION;
    this.ID_RESOURCE_RESOURCE_ID = XACML1.ID_RESOURCE_RESOURCE_ID;
    this.ID_RESOURCE_SIMPLE_FILE_NAME = XACML1.ID_RESOURCE_SIMPLE_FILE_NAME;
    this.ID_ACTION_ACTION_ID = XACML1.ID_ACTION_ACTION_ID;
    this.ID_ACTION_IMPLIED_ACTION = XACML1.ID_ACTION_IMPLIED_ACTION;
    /*
     * There does not seem to be a place in the spec where the standard categories are defined, so I will put
     * them here for now
     */
    this.ID_ATTRIBUTE_CATEGORY_RESOURCE = Utils.resolveURI(this.ID_ATTRIBUTE_CATEGORY, XACML.RESOURCE);
    this.ID_ATTRIBUTE_CATEGORY_ACTION = Utils.resolveURI(this.ID_ATTRIBUTE_CATEGORY, XACML.ACTION);
    this.ID_ATTRIBUTE_CATEGORY_ENVIRONMENT = Utils.resolveURI(this.ID_ATTRIBUTE_CATEGORY, XACML.ENVIRONMENT);

    /*
     * Section 10.2.7 Data-types
     */
    this.ID_DATATYPE_STRING = XACML.ID_DATATYPE_STRING;
    this.ID_DATATYPE_BOOLEAN = XACML.ID_DATATYPE_BOOLEAN;
    this.ID_DATATYPE_INTEGER = XACML.ID_DATATYPE_INTEGER;
    this.ID_DATATYPE_DOUBLE = XACML.ID_DATATYPE_DOUBLE;
    this.ID_DATATYPE_TIME = XACML.ID_DATATYPE_TIME;
    this.ID_DATATYPE_DATE = XACML.ID_DATATYPE_DATE;
    this.ID_DATATYPE_DATETIME = XACML.ID_DATATYPE_DATETIME;
    this.ID_DATATYPE_DAYTIMEDURATION = XACML.ID_DATATYPE_DAYTIMEDURATION;
    this.ID_DATATYPE_YEARMONTHDURATION = XACML.ID_DATATYPE_YEARMONTHDURATION;
    this.ID_DATATYPE_ANYURI = XACML.ID_DATATYPE_ANYURI;
    this.ID_DATATYPE_HEXBINARY = XACML.ID_DATATYPE_HEXBINARY;
    this.ID_DATATYPE_BASE64BINARY = XACML.ID_DATATYPE_BASE64BINARY;
    this.ID_DATATYPE_RFC822NAME = XACML1.ID_DATATYPE_RFC822NAME;
    this.ID_DATATYPE_X500NAME = XACML1.ID_DATATYPE_X500NAME;
    this.ID_DATATYPE_IPADDRESS = XACML2.ID_DATATYPE_IPADDRESS;
    this.ID_DATATYPE_DNSNAME = XACML2.ID_DATATYPE_DNSNAME;

    this.ID_DATATYPE = Utils.resolveURI(this.ID_XACML, XACML.DATA_TYPE);
    this.ID_DATATYPE_XPATHEXPRESSION = Utils.resolveURI(this.ID_DATATYPE, "xpathExpression");

    /*
     * Section 10.2.8 Functions
     */

    this.ID_FUNCTION_STRING_EQUAL = XACML1.ID_FUNCTION_STRING_EQUAL;
    this.ID_FUNCTION_BOOLEAN_EQUAL = XACML1.ID_FUNCTION_BOOLEAN_EQUAL;
    this.ID_FUNCTION_INTEGER_EQUAL = XACML1.ID_FUNCTION_INTEGER_EQUAL;
    this.ID_FUNCTION_DOUBLE_EQUAL = XACML1.ID_FUNCTION_DOUBLE_EQUAL;
    this.ID_FUNCTION_DATE_EQUAL = XACML1.ID_FUNCTION_DATE_EQUAL;
    this.ID_FUNCTION_TIME_EQUAL = XACML1.ID_FUNCTION_TIME_EQUAL;
    this.ID_FUNCTION_DATETIME_EQUAL = XACML1.ID_FUNCTION_DATETIME_EQUAL;
    this.ID_FUNCTION_DAYTIMEDURATION_EQUAL = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-equal");
    this.ID_FUNCTION_YEARMONTHDURATION_EQUAL = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-equal");
    this.ID_FUNCTION_STRING_EQUAL_IGNORE_CASE = Utils.resolveURI(this.ID_FUNCTION, "string-equal-ignore-case");
    this.ID_FUNCTION_ANYURI_EQUAL = XACML1.ID_FUNCTION_ANYURI_EQUAL;
    this.ID_FUNCTION_X500NAME_EQUAL = XACML1.ID_FUNCTION_X500NAME_EQUAL;
    this.ID_FUNCTION_RFC822NAME_EQUAL = XACML1.ID_FUNCTION_RFC822NAME_EQUAL;
    this.ID_FUNCTION_HEXBINARY_EQUAL = XACML1.ID_FUNCTION_HEXBINARY_EQUAL;
    this.ID_FUNCTION_BASE64BINARY_EQUAL = XACML1.ID_FUNCTION_BASE64BINARY_EQUAL;
    this.ID_FUNCTION_INTEGER_ADD = XACML1.ID_FUNCTION_INTEGER_ADD;
    this.ID_FUNCTION_DOUBLE_ADD = XACML1.ID_FUNCTION_DOUBLE_ADD;
    this.ID_FUNCTION_INTEGER_SUBTRACT = XACML1.ID_FUNCTION_INTEGER_SUBTRACT;
    this.ID_FUNCTION_DOUBLE_SUBTRACT = XACML1.ID_FUNCTION_DOUBLE_SUBTRACT;
    this.ID_FUNCTION_INTEGER_MULTIPLY = XACML1.ID_FUNCTION_INTEGER_MULTIPLY;
    this.ID_FUNCTION_DOUBLE_MULTIPLY = XACML1.ID_FUNCTION_DOUBLE_MULTIPLY;
    this.ID_FUNCTION_INTEGER_DIVIDE = XACML1.ID_FUNCTION_INTEGER_DIVIDE;
    this.ID_FUNCTION_DOUBLE_DIVIDE = XACML1.ID_FUNCTION_DOUBLE_DIVIDE;
    this.ID_FUNCTION_INTEGER_MOD = XACML1.ID_FUNCTION_INTEGER_MOD;
    this.ID_FUNCTION_INTEGER_ABS = XACML1.ID_FUNCTION_INTEGER_ABS;
    this.ID_FUNCTION_DOUBLE_ABS = XACML1.ID_FUNCTION_DOUBLE_ABS;
    this.ID_FUNCTION_ROUND = XACML1.ID_FUNCTION_ROUND;
    this.ID_FUNCTION_FLOOR = XACML1.ID_FUNCTION_FLOOR;
    this.ID_FUNCTION_STRING_NORMALIZE_SPACE = XACML1.ID_FUNCTION_STRING_NORMALIZE_SPACE;
    this.ID_FUNCTION_STRING_NORMALIZE_TO_LOWER_CASE = XACML1.ID_FUNCTION_STRING_NORMALIZE_TO_LOWER_CASE;
    this.ID_FUNCTION_DOUBLE_TO_INTEGER = XACML1.ID_FUNCTION_DOUBLE_TO_INTEGER;
    this.ID_FUNCTION_INTEGER_TO_DOUBLE = XACML1.ID_FUNCTION_INTEGER_TO_DOUBLE;
    this.ID_FUNCTION_OR = XACML1.ID_FUNCTION_OR;
    this.ID_FUNCTION_AND = XACML1.ID_FUNCTION_AND;
    this.ID_FUNCTION_N_OF = XACML1.ID_FUNCTION_N_OF;
    this.ID_FUNCTION_NOT = XACML1.ID_FUNCTION_NOT;
    this.ID_FUNCTION_PRESENT = XACML1.ID_FUNCTION_PRESENT;
    this.ID_FUNCTION_INTEGER_GREATER_THAN = XACML1.ID_FUNCTION_INTEGER_GREATER_THAN;
    this.ID_FUNCTION_INTEGER_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_INTEGER_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_INTEGER_LESS_THAN = XACML1.ID_FUNCTION_INTEGER_LESS_THAN;
    this.ID_FUNCTION_INTEGER_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_INTEGER_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_DOUBLE_GREATER_THAN = XACML1.ID_FUNCTION_DOUBLE_GREATER_THAN;
    this.ID_FUNCTION_DOUBLE_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DOUBLE_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_DOUBLE_LESS_THAN = XACML1.ID_FUNCTION_DOUBLE_LESS_THAN;
    this.ID_FUNCTION_DOUBLE_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DOUBLE_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_DATETIME_ADD_DAYTIMEDURATION = Utils.resolveURI(this.ID_FUNCTION, "dateTime-add-dayTimeDuration");
    this.ID_FUNCTION_DATETIME_ADD_YEARMONTHDURATION = Utils.resolveURI(this.ID_FUNCTION, "dateTime-add-yearMonthDuration");
    this.ID_FUNCTION_DATETIME_SUBTRACT_DAYTIMEDURATION = Utils.resolveURI(this.ID_FUNCTION, "dateTime-subtract-dayTimeDuration");
    this.ID_FUNCTION_DATETIME_SUBTRACT_YEARMONTHDURATION = Utils.resolveURI(this.ID_FUNCTION, "dateTime-subtract-yearMonthDuration");
    this.ID_FUNCTION_DATE_ADD_YEARMONTHDURATION = Utils.resolveURI(this.ID_FUNCTION, "date-add-yearMonthDuration");
    this.ID_FUNCTION_DATE_SUBTRACT_YEARMONTHDURATION = Utils.resolveURI(this.ID_FUNCTION, "date-subtract-yearMonthDuration");
    this.ID_FUNCTION_STRING_GREATER_THAN = XACML1.ID_FUNCTION_STRING_GREATER_THAN;
    this.ID_FUNCTION_STRING_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_STRING_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_STRING_LESS_THAN = XACML1.ID_FUNCTION_STRING_LESS_THAN;
    this.ID_FUNCTION_STRING_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_STRING_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_TIME_GREATER_THAN = XACML1.ID_FUNCTION_TIME_GREATER_THAN;
    this.ID_FUNCTION_TIME_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_TIME_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_TIME_LESS_THAN = XACML1.ID_FUNCTION_TIME_LESS_THAN;
    this.ID_FUNCTION_TIME_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_TIME_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_TIME_IN_RANGE = XACML2.ID_FUNCTION_TIME_IN_RANGE;
    this.ID_FUNCTION_DATETIME_GREATER_THAN = XACML1.ID_FUNCTION_DATETIME_GREATER_THAN;
    this.ID_FUNCTION_DATETIME_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DATETIME_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_DATETIME_LESS_THAN = XACML1.ID_FUNCTION_DATETIME_LESS_THAN;
    this.ID_FUNCTION_DATETIME_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DATETIME_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_DATE_GREATER_THAN = XACML1.ID_FUNCTION_DATE_GREATER_THAN;
    this.ID_FUNCTION_DATE_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DATE_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_DATE_LESS_THAN = XACML1.ID_FUNCTION_DATE_LESS_THAN;
    this.ID_FUNCTION_DATE_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DATE_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_STRING_ONE_AND_ONLY = XACML1.ID_FUNCTION_STRING_ONE_AND_ONLY;
    this.ID_FUNCTION_STRING_BAG_SIZE = XACML1.ID_FUNCTION_STRING_BAG_SIZE;
    this.ID_FUNCTION_STRING_IS_IN = XACML1.ID_FUNCTION_STRING_IS_IN;
    this.ID_FUNCTION_STRING_BAG = XACML1.ID_FUNCTION_STRING_BAG;
    this.ID_FUNCTION_BOOLEAN_ONE_AND_ONLY = XACML1.ID_FUNCTION_BOOLEAN_ONE_AND_ONLY;
    this.ID_FUNCTION_BOOLEAN_BAG_SIZE = XACML1.ID_FUNCTION_BOOLEAN_BAG_SIZE;
    this.ID_FUNCTION_BOOLEAN_IS_IN = XACML1.ID_FUNCTION_BOOLEAN_IS_IN;
    this.ID_FUNCTION_BOOLEAN_BAG = XACML1.ID_FUNCTION_BOOLEAN_BAG;
    this.ID_FUNCTION_INTEGER_ONE_AND_ONLY = XACML1.ID_FUNCTION_INTEGER_ONE_AND_ONLY;
    this.ID_FUNCTION_INTEGER_BAG_SIZE = XACML1.ID_FUNCTION_INTEGER_BAG_SIZE;
    this.ID_FUNCTION_INTEGER_IS_IN = XACML1.ID_FUNCTION_INTEGER_IS_IN;
    this.ID_FUNCTION_INTEGER_BAG = XACML1.ID_FUNCTION_INTEGER_BAG;
    this.ID_FUNCTION_DOUBLE_ONE_AND_ONLY = XACML1.ID_FUNCTION_DOUBLE_ONE_AND_ONLY;
    this.ID_FUNCTION_DOUBLE_BAG_SIZE = XACML1.ID_FUNCTION_DOUBLE_BAG_SIZE;
    this.ID_FUNCTION_DOUBLE_IS_IN = XACML1.ID_FUNCTION_DOUBLE_IS_IN;
    this.ID_FUNCTION_DOUBLE_BAG = XACML1.ID_FUNCTION_DOUBLE_BAG;
    this.ID_FUNCTION_TIME_ONE_AND_ONLY = XACML1.ID_FUNCTION_TIME_ONE_AND_ONLY;
    this.ID_FUNCTION_TIME_BAG_SIZE = XACML1.ID_FUNCTION_TIME_BAG_SIZE;
    this.ID_FUNCTION_TIME_IS_IN = XACML1.ID_FUNCTION_TIME_IS_IN;
    this.ID_FUNCTION_TIME_BAG = XACML1.ID_FUNCTION_TIME_BAG;
    this.ID_FUNCTION_DATE_ONE_AND_ONLY = XACML1.ID_FUNCTION_DATE_ONE_AND_ONLY;
    this.ID_FUNCTION_DATE_BAG_SIZE = XACML1.ID_FUNCTION_DATE_BAG_SIZE;
    this.ID_FUNCTION_DATE_IS_IN = XACML1.ID_FUNCTION_DATE_IS_IN;
    this.ID_FUNCTION_DATE_BAG = XACML1.ID_FUNCTION_DATE_BAG;
    this.ID_FUNCTION_DATETIME_ONE_AND_ONLY = XACML1.ID_FUNCTION_DATETIME_ONE_AND_ONLY;
    this.ID_FUNCTION_DATETIME_BAG_SIZE = XACML1.ID_FUNCTION_DATETIME_BAG_SIZE;
    this.ID_FUNCTION_DATETIME_IS_IN = XACML1.ID_FUNCTION_DATETIME_IS_IN;
    this.ID_FUNCTION_DATETIME_BAG = XACML1.ID_FUNCTION_DATETIME_BAG;
    this.ID_FUNCTION_ANYURI_ONE_AND_ONLY = XACML1.ID_FUNCTION_ANYURI_ONE_AND_ONLY;
    this.ID_FUNCTION_ANYURI_BAG_SIZE = XACML1.ID_FUNCTION_ANYURI_BAG_SIZE;
    this.ID_FUNCTION_ANYURI_IS_IN = XACML1.ID_FUNCTION_ANYURI_IS_IN;
    this.ID_FUNCTION_ANYURI_BAG = XACML1.ID_FUNCTION_ANYURI_BAG;
    this.ID_FUNCTION_HEXBINARY_ONE_AND_ONLY = XACML1.ID_FUNCTION_HEXBINARY_ONE_AND_ONLY;
    this.ID_FUNCTION_HEXBINARY_BAG_SIZE = XACML1.ID_FUNCTION_HEXBINARY_BAG_SIZE;
    this.ID_FUNCTION_HEXBINARY_IS_IN = XACML1.ID_FUNCTION_HEXBINARY_IS_IN;
    this.ID_FUNCTION_HEXBINARY_BAG = XACML1.ID_FUNCTION_HEXBINARY_BAG;
    this.ID_FUNCTION_BASE64BINARY_ONE_AND_ONLY = XACML1.ID_FUNCTION_BASE64BINARY_ONE_AND_ONLY;
    this.ID_FUNCTION_BASE64BINARY_BAG_SIZE = XACML1.ID_FUNCTION_BASE64BINARY_BAG_SIZE;
    this.ID_FUNCTION_BASE64BINARY_IS_IN = XACML1.ID_FUNCTION_BASE64BINARY_IS_IN;
    this.ID_FUNCTION_BASE64BINARY_BAG = XACML1.ID_FUNCTION_BASE64BINARY_BAG;
    this.ID_FUNCTION_DAYTIMEDURATION_ONE_AND_ONLY = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-one-and-only");
    this.ID_FUNCTION_DAYTIMEDURATION_BAG_SIZE = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-bag-size");
    this.ID_FUNCTION_DAYTIMEDURATION_IS_IN = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-is-in");
    this.ID_FUNCTION_DAYTIMEDURATION_BAG = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-bag");
    this.ID_FUNCTION_YEARMONTHDURATION_ONE_AND_ONLY = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-one-and-only");
    this.ID_FUNCTION_YEARMONTHDURATION_BAG_SIZE = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-bag-size");
    this.ID_FUNCTION_YEARMONTHDURATION_IS_IN = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-is-in");
    this.ID_FUNCTION_YEARMONTHDURATION_BAG = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-bag");
    this.ID_FUNCTION_X500NAME_ONE_AND_ONLY = XACML1.ID_FUNCTION_X500NAME_ONE_AND_ONLY;
    this.ID_FUNCTION_X500NAME_BAG_SIZE = XACML1.ID_FUNCTION_X500NAME_BAG_SIZE;
    this.ID_FUNCTION_X500NAME_IS_IN = XACML1.ID_FUNCTION_X500NAME_IS_IN;
    this.ID_FUNCTION_X500NAME_BAG = XACML1.ID_FUNCTION_X500NAME_BAG;
    this.ID_FUNCTION_RFC822NAME_ONE_AND_ONLY = XACML1.ID_FUNCTION_RFC822NAME_ONE_AND_ONLY;
    this.ID_FUNCTION_RFC822NAME_BAG_SIZE = XACML1.ID_FUNCTION_RFC822NAME_BAG_SIZE;
    this.ID_FUNCTION_RFC822NAME_IS_IN = XACML1.ID_FUNCTION_RFC822NAME_IS_IN;
    this.ID_FUNCTION_RFC822NAME_BAG = XACML1.ID_FUNCTION_RFC822NAME_BAG;
    this.ID_FUNCTION_IPADDRESS_ONE_AND_ONLY = XACML2.ID_FUNCTION_IPADDRESS_ONE_AND_ONLY;
    this.ID_FUNCTION_IPADDRESS_BAG_SIZE = XACML2.ID_FUNCTION_IPADDRESS_BAG_SIZE;
    this.ID_FUNCTION_IPADDRESS_IS_IN = XACML2.ID_FUNCTION_IPADDRESS_IS_IN;
    this.ID_FUNCTION_IPADDRESS_BAG = XACML2.ID_FUNCTION_IPADDRESS_BAG;
    this.ID_FUNCTION_DNSNAME_ONE_AND_ONLY = XACML2.ID_FUNCTION_DNSNAME_ONE_AND_ONLY;
    this.ID_FUNCTION_DNSNAME_BAG_SIZE = XACML2.ID_FUNCTION_DNSNAME_BAG_SIZE;
    this.ID_FUNCTION_DNSNAME_IS_IN = XACML2.ID_FUNCTION_DNSNAME_IS_IN;
    this.ID_FUNCTION_DNSNAME_BAG = XACML2.ID_FUNCTION_DNSNAME_BAG;
    this.ID_FUNCTION_STRING_CONCATENATE = XACML2.ID_FUNCTION_STRING_CONCATENATE;
    this.ID_FUNCTION_BOOLEAN_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "boolean-from-string");
    this.ID_FUNCTION_STRING_FROM_BOOLEAN = Utils.resolveURI(this.ID_FUNCTION, "string-from-boolean");
    this.ID_FUNCTION_INTEGER_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "integer-from-string");
    this.ID_FUNCTION_STRING_FROM_INTEGER = Utils.resolveURI(this.ID_FUNCTION, "string-from-integer");
    this.ID_FUNCTION_DOUBLE_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "double-from-string");
    this.ID_FUNCTION_STRING_FROM_DOUBLE = Utils.resolveURI(this.ID_FUNCTION, "string-from-double");
    this.ID_FUNCTION_TIME_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "time-from-string");
    this.ID_FUNCTION_STRING_FROM_TIME = Utils.resolveURI(this.ID_FUNCTION, "string-from-time");
    this.ID_FUNCTION_DATE_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "date-from-string");
    this.ID_FUNCTION_STRING_FROM_DATE = Utils.resolveURI(this.ID_FUNCTION, "string-from-date");
    this.ID_FUNCTION_DATETIME_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "dateTime-from-string");
    this.ID_FUNCTION_STRING_FROM_DATETIME = Utils.resolveURI(this.ID_FUNCTION, "string-from-dateTime");
    this.ID_FUNCTION_ANYURI_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "anyURI-from-string");
    this.ID_FUNCTION_STRING_FROM_ANYURI = Utils.resolveURI(this.ID_FUNCTION, "string-from-anyURI");
    this.ID_FUNCTION_DAYTIMEDURATION_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-from-string");
    this.ID_FUNCTION_STRING_FROM_DAYTIMEDURATION = Utils.resolveURI(this.ID_FUNCTION, "string-from-dayTimeDuration");
    this.ID_FUNCTION_YEARMONTHDURATION_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-from-string");
    this.ID_FUNCTION_STRING_FROM_YEARMONTHDURATION = Utils.resolveURI(this.ID_FUNCTION, "string-from-yearMonthDuration");
    this.ID_FUNCTION_X500NAME_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "x500Name-from-string");
    this.ID_FUNCTION_STRING_FROM_X500NAME = Utils.resolveURI(this.ID_FUNCTION, "string-from-x500Name");
    this.ID_FUNCTION_RFC822NAME_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "rfc822Name-from-string");
    this.ID_FUNCTION_STRING_FROM_RFC822NAME = Utils.resolveURI(this.ID_FUNCTION, "string-from-rfc822Name");
    this.ID_FUNCTION_IPADDRESS_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-from-string");
    this.ID_FUNCTION_STRING_FROM_IPADDRESS = Utils.resolveURI(this.ID_FUNCTION, "string-from-ipAddress");
    this.ID_FUNCTION_DNSNAME_FROM_STRING = Utils.resolveURI(this.ID_FUNCTION, "dnsName-from-string");
    this.ID_FUNCTION_STRING_FROM_DNSNAME = Utils.resolveURI(this.ID_FUNCTION, "string-from-dnsName");
    this.ID_FUNCTION_STRING_STARTS_WITH = Utils.resolveURI(this.ID_FUNCTION, "string-starts-with");
    this.ID_FUNCTION_ANYURI_STARTS_WITH = Utils.resolveURI(this.ID_FUNCTION, "anyURI-starts-with");
    this.ID_FUNCTION_STRING_ENDS_WITH = Utils.resolveURI(this.ID_FUNCTION, "string-ends-with");
    this.ID_FUNCTION_ANYURI_ENDS_WITH = Utils.resolveURI(this.ID_FUNCTION, "anyURI-ends-with");
    this.ID_FUNCTION_STRING_CONTAINS = Utils.resolveURI(this.ID_FUNCTION, "string-contains");
    this.ID_FUNCTION_ANYURI_CONTAINS = Utils.resolveURI(this.ID_FUNCTION, "anyURI-contains");
    this.ID_FUNCTION_STRING_SUBSTRING = Utils.resolveURI(this.ID_FUNCTION, "string-substring");
    this.ID_FUNCTION_ANYURI_SUBSTRING = Utils.resolveURI(this.ID_FUNCTION, "anyURI-substring");
    this.ID_FUNCTION_ANY_OF = Utils.resolveURI(this.ID_FUNCTION, "any-of");
    this.ID_FUNCTION_ALL_OF = Utils.resolveURI(this.ID_FUNCTION, "all-of");
    this.ID_FUNCTION_ANY_OF_ANY = Utils.resolveURI(this.ID_FUNCTION, "any-of-any");
    this.ID_FUNCTION_ALL_OF_ANY = XACML1.ID_FUNCTION_ALL_OF_ANY;
    this.ID_FUNCTION_ANY_OF_ALL = XACML1.ID_FUNCTION_ANY_OF_ALL;
    this.ID_FUNCTION_ALL_OF_ALL = XACML1.ID_FUNCTION_ALL_OF_ALL;
    this.ID_FUNCTION_MAP = Utils.resolveURI(this.ID_FUNCTION, "map");
    this.ID_FUNCTION_X500NAME_MATCH = XACML1.ID_FUNCTION_X500NAME_MATCH;
    this.ID_FUNCTION_RFC822NAME_MATCH = XACML1.ID_FUNCTION_RFC822NAME_MATCH;
    this.ID_FUNCTION_STRING_REGEXP_MATCH = XACML1.ID_FUNCTION_STRING_REGEXP_MATCH;
    this.ID_FUNCTION_ANYURI_REGEXP_MATCH = XACML2.ID_FUNCTION_ANYURI_REGEXP_MATCH;
    this.ID_FUNCTION_IPADDRESS_REGEXP_MATCH = XACML2.ID_FUNCTION_IPADDRESS_REGEXP_MATCH;
    this.ID_FUNCTION_DNSNAME_REGEXP_MATCH = XACML2.ID_FUNCTION_DNSNAME_REGEXP_MATCH;
    this.ID_FUNCTION_RFC822NAME_REGEXP_MATCH = XACML2.ID_FUNCTION_RFC822NAME_REGEXP_MATCH;
    this.ID_FUNCTION_X500NAME_REGEXP_MATCH = XACML2.ID_FUNCTION_X500NAME_REGEXP_MATCH;
    this.ID_FUNCTION_XPATH_NODE_COUNT = Utils.resolveURI(this.ID_FUNCTION, "xpath-node-count");
    this.ID_FUNCTION_XPATH_NODE_EQUAL = Utils.resolveURI(this.ID_FUNCTION, "xpath-node-equal");
    this.ID_FUNCTION_XPATH_NODE_MATCH = Utils.resolveURI(this.ID_FUNCTION, "xpath-node-match");
    this.ID_FUNCTION_STRING_INTERSECTION = XACML1.ID_FUNCTION_STRING_INTERSECTION;
    this.ID_FUNCTION_STRING_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_STRING_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_STRING_UNION = XACML1.ID_FUNCTION_STRING_UNION;
    this.ID_FUNCTION_STRING_SUBSET = XACML1.ID_FUNCTION_STRING_SUBSET;
    this.ID_FUNCTION_STRING_SET_EQUALS = XACML1.ID_FUNCTION_STRING_SET_EQUALS;
    this.ID_FUNCTION_BOOLEAN_INTERSECTION = XACML1.ID_FUNCTION_BOOLEAN_INTERSECTION;
    this.ID_FUNCTION_BOOLEAN_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_BOOLEAN_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_BOOLEAN_UNION = XACML1.ID_FUNCTION_BOOLEAN_UNION;
    this.ID_FUNCTION_BOOLEAN_SUBSET = XACML1.ID_FUNCTION_BOOLEAN_SUBSET;
    this.ID_FUNCTION_BOOLEAN_SET_EQUALS = XACML1.ID_FUNCTION_BOOLEAN_SET_EQUALS;
    this.ID_FUNCTION_INTEGER_INTERSECTION = XACML1.ID_FUNCTION_INTEGER_INTERSECTION;
    this.ID_FUNCTION_INTEGER_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_INTEGER_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_INTEGER_UNION = XACML1.ID_FUNCTION_INTEGER_UNION;
    this.ID_FUNCTION_INTEGER_SUBSET = XACML1.ID_FUNCTION_INTEGER_SUBSET;
    this.ID_FUNCTION_INTEGER_SET_EQUALS = XACML1.ID_FUNCTION_INTEGER_SET_EQUALS;
    this.ID_FUNCTION_DOUBLE_INTERSECTION = XACML1.ID_FUNCTION_DOUBLE_INTERSECTION;
    this.ID_FUNCTION_DOUBLE_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_DOUBLE_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_DOUBLE_UNION = XACML1.ID_FUNCTION_DOUBLE_UNION;
    this.ID_FUNCTION_DOUBLE_SUBSET = XACML1.ID_FUNCTION_DOUBLE_SUBSET;
    this.ID_FUNCTION_DOUBLE_SET_EQUALS = XACML1.ID_FUNCTION_DOUBLE_SET_EQUALS;
    this.ID_FUNCTION_TIME_INTERSECTION = XACML1.ID_FUNCTION_TIME_INTERSECTION;
    this.ID_FUNCTION_TIME_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_TIME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_TIME_UNION = XACML1.ID_FUNCTION_TIME_UNION;
    this.ID_FUNCTION_TIME_SUBSET = XACML1.ID_FUNCTION_TIME_SUBSET;
    this.ID_FUNCTION_TIME_SET_EQUALS = XACML1.ID_FUNCTION_TIME_SET_EQUALS;
    this.ID_FUNCTION_DATE_INTERSECTION = XACML1.ID_FUNCTION_DATE_INTERSECTION;
    this.ID_FUNCTION_DATE_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_DATE_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_DATE_UNION = XACML1.ID_FUNCTION_DATE_UNION;
    this.ID_FUNCTION_DATE_SUBSET = XACML1.ID_FUNCTION_DATE_SUBSET;
    this.ID_FUNCTION_DATE_SET_EQUALS = XACML1.ID_FUNCTION_DATE_SET_EQUALS;
    this.ID_FUNCTION_DATETIME_INTERSECTION = XACML1.ID_FUNCTION_DATETIME_INTERSECTION;
    this.ID_FUNCTION_DATETIME_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_DATETIME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_DATETIME_UNION = XACML1.ID_FUNCTION_DATETIME_UNION;
    this.ID_FUNCTION_DATETIME_SUBSET = XACML1.ID_FUNCTION_DATETIME_SUBSET;
    this.ID_FUNCTION_DATETIME_SET_EQUALS = XACML1.ID_FUNCTION_DATETIME_SET_EQUALS;
    this.ID_FUNCTION_ANYURI_INTERSECTION = XACML1.ID_FUNCTION_ANYURI_INTERSECTION;
    this.ID_FUNCTION_ANYURI_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_ANYURI_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_ANYURI_UNION = XACML1.ID_FUNCTION_ANYURI_UNION;
    this.ID_FUNCTION_ANYURI_SUBSET = XACML1.ID_FUNCTION_ANYURI_SUBSET;
    this.ID_FUNCTION_ANYURI_SET_EQUALS = XACML1.ID_FUNCTION_ANYURI_SET_EQUALS;
    this.ID_FUNCTION_HEXBINARY_INTERSECTION = XACML1.ID_FUNCTION_HEXBINARY_INTERSECTION;
    this.ID_FUNCTION_HEXBINARY_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_HEXBINARY_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_HEXBINARY_UNION = XACML1.ID_FUNCTION_HEXBINARY_UNION;
    this.ID_FUNCTION_HEXBINARY_SUBSET = XACML1.ID_FUNCTION_HEXBINARY_SUBSET;
    this.ID_FUNCTION_HEXBINARY_SET_EQUALS = XACML1.ID_FUNCTION_HEXBINARY_SET_EQUALS;
    this.ID_FUNCTION_BASE64BINARY_INTERSECTION = XACML1.ID_FUNCTION_BASE64BINARY_INTERSECTION;
    this.ID_FUNCTION_BASE64BINARY_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_BASE64BINARY_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_BASE64BINARY_UNION = XACML1.ID_FUNCTION_BASE64BINARY_UNION;
    this.ID_FUNCTION_BASE64BINARY_SUBSET = XACML1.ID_FUNCTION_BASE64BINARY_SUBSET;
    this.ID_FUNCTION_BASE64BINARY_SET_EQUALS = XACML1.ID_FUNCTION_BASE64BINARY_SET_EQUALS;
    this.ID_FUNCTION_DAYTIMEDURATION_INTERSECTION = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-intersection");
    this.ID_FUNCTION_DAYTIMEDURATION_AT_LEAST_ONE_MEMBER_OF = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-at-least-one-member-of");
    this.ID_FUNCTION_DAYTIMEDURATION_UNION = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-union");
    this.ID_FUNCTION_DAYTIMEDURATION_SUBSET = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-subset");
    this.ID_FUNCTION_DAYTIMEDURATION_SET_EQUALS = Utils.resolveURI(this.ID_FUNCTION, "dayTimeDuration-set-equals");
    this.ID_FUNCTION_YEARMONTHDURATION_INTERSECTION = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-intersection");
    this.ID_FUNCTION_YEARMONTHDURATION_AT_LEAST_ONE_MEMBER_OF = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-at-least-one-member-of");
    this.ID_FUNCTION_YEARMONTHDURATION_UNION = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-union");
    this.ID_FUNCTION_YEARMONTHDURATION_SUBSET = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-subset");
    this.ID_FUNCTION_YEARMONTHDURATION_SET_EQUALS = Utils.resolveURI(this.ID_FUNCTION, "yearMonthDuration-set-equals");
    this.ID_FUNCTION_X500NAME_INTERSECTION = XACML1.ID_FUNCTION_X500NAME_INTERSECTION;
    this.ID_FUNCTION_X500NAME_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_X500NAME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_X500NAME_UNION = XACML1.ID_FUNCTION_X500NAME_UNION;
    this.ID_FUNCTION_X500NAME_SUBSET = XACML1.ID_FUNCTION_X500NAME_SUBSET;
    this.ID_FUNCTION_X500NAME_SET_EQUALS = XACML1.ID_FUNCTION_X500NAME_SET_EQUALS;
    this.ID_FUNCTION_RFC822NAME_INTERSECTION = XACML1.ID_FUNCTION_RFC822NAME_INTERSECTION;
    this.ID_FUNCTION_RFC822NAME_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_RFC822NAME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_RFC822NAME_UNION = XACML1.ID_FUNCTION_RFC822NAME_UNION;
    this.ID_FUNCTION_RFC822NAME_SUBSET = XACML1.ID_FUNCTION_RFC822NAME_SUBSET;
    this.ID_FUNCTION_RFC822NAME_SET_EQUALS = XACML1.ID_FUNCTION_RFC822NAME_SET_EQUALS;
    this.ID_FUNCTION_IPADDRESS_INTERSECTION = XACML2.ID_FUNCTION_IPADDRESS_INTERSECTION;
    this.ID_FUNCTION_IPADDRESS_AT_LEAST_ONE_MEMBER_OF = XACML2.ID_FUNCTION_IPADDRESS_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_IPADDRESS_UNION = XACML2.ID_FUNCTION_IPADDRESS_UNION;
    this.ID_FUNCTION_IPADDRESS_SUBSET = XACML2.ID_FUNCTION_IPADDRESS_SUBSET;
    this.ID_FUNCTION_IPADDRESS_SET_EQUALS = XACML2.ID_FUNCTION_IPADDRESS_SET_EQUALS;
    this.ID_FUNCTION_DNSNAME_INTERSECTION = XACML2.ID_FUNCTION_DNSNAME_INTERSECTION;
    this.ID_FUNCTION_DNSNAME_AT_LEAST_ONE_MEMBER_OF = XACML2.ID_FUNCTION_DNSNAME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_DNSNAME_UNION = XACML2.ID_FUNCTION_DNSNAME_UNION;
    this.ID_FUNCTION_DNSNAME_SUBSET = XACML2.ID_FUNCTION_DNSNAME_SUBSET;
    this.ID_FUNCTION_DNSNAME_SET_EQUALS = XACML2.ID_FUNCTION_DNSNAME_SET_EQUALS;
    this.ID_FUNCTION_ACCESS_PERMITTED = Utils.resolveURI(this.ID_FUNCTION, "access-permitted");

    /*
     * Profiles
     */
    this.ID_PROFILE = Utils.resolveURI(this.ID_XACML, XACML.PROFILE);
    this.ID_PROFILES = Utils.resolveURI(this.ID_XACML, XACML.PROFILES);

    /*
     * XACML v3.0 Administration and Delegation Profile Version 1.0
     */
    this.ID_PROFILE_ADMINISTRATION_REDUCTION = Utils.resolveURI(this.ID_PROFILE, "administration:reduction");
    this.ID_DELEGATION = Utils.resolveURI(this.ID_XACML, "delegation");
    this.ID_DELEGATION_DECISION = Utils.resolveURI(this.ID_DELEGATION, "decision");
    this.ID_ATTRIBUTE_CATEGORY_DELEGATE = Utils.resolveURI(this.ID_ATTRIBUTE_CATEGORY, "delegate");
    this.ID_ATTRIBUTE_CATEGORY_DELEGATION_INFO = Utils.resolveURI(this.ID_ATTRIBUTE_CATEGORY, "delegation-info");
    this.ID_ATTRIBUTE_CATEGORY_DELEGATED = Utils.resolveURI(this.ID_ATTRIBUTE_CATEGORY, "delegated");

    /*
     * SAML 2.0 Profile of XACML, Version 2.0
     */
    this.ID_PROFILE_SAML2_0_V2 = Utils.resolveURI(this.ID_PROFILE, "saml2.0:v2");
    this.ID_PROFILE_SAML2_0_V2_POLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "policies");
    this.ID_PROFILE_SAML2_0_V2_ADVICESAML = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "adviceSAML");
    this.ID_PROFILE_SAML2_0_V2_AUTHZTOKEN = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "authzToken");
    this.ID_PROFILE_SAML2_0_V2_ATTRS_ALL = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "attrs:all");
    this.ID_PROFILE_SAML2_0_V2_SOAP = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "SOAP");
    this.ID_PROFILE_SAML2_0_V2_SOAP_AUTHZQUERY = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_SOAP, "authzQuery");
    this.ID_PROFILE_SAML2_0_V2_SOAP_ATTRASSERTION = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_SOAP, "attrAssertion");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "authzDecision");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION_NOPOLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION, "noPolicies");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION_WITHPOLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION, "withPolicies");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "authzDecisionWSTrust");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST_WITHPOLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST, "withPolicies");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST_NOPOLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST, "noPolicies");
    this.ID_PROFILE_SAML2_0_V2_SCHEMA = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "schema");
    this.ID_PROFILE_SAML2_0_V2_SCHEMA_ASSERTION = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_SCHEMA, "assertion");
    this.ID_PROFILE_SAML2_0_V2_SCHEMA_PROTOCOL = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_SCHEMA, "protocol");

    /*
     * XACML v3.0 Hierarchical Resource Profile Version 1.0
     */
    this.ID_PROFILE_HIERARCHICAL = Utils.resolveURI(this.ID_PROFILE, "hierarchical");
    this.ID_PROFILE_HIERARCHICAL_ATTRIBUTE_NODE_ID = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "attribute-node-id");
    this.ID_PROFILE_HIERARCHICAL_XML_NODE_ID = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "xml-node-id");
    this.ID_PROFILE_HIERARCHICAL_URI_NODE_ID = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "URI-node-id");
    this.ID_PROFILE_HIERARCHICAL_URI_REFERENCE_NODE_ID = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "URI-reference-node-id");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_ID = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "non-xml-node-id");
    this.ID_PROFILE_HIERARCHICAL_XML_NODE_REQ = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "xml-node-req");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "non-xml-node-req");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ_RESOURCE_PARENT = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ, "resource-parent");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ_RESOURCE_ANCESTOR = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ, "resource-ancestor");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ_RESOURCE_ANCESTOR_OR_SELF = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ, "resource-ancestor-or-self");

    this.ID_CONTENT_SELECTOR = Utils.resolveURI(this.ID_XACML, "content-selector");
    this.ID_RESOURCE_DOCUMENT_ID = XACML2.ID_RESOURCE_DOCUMENT_ID;
    this.ID_RESOURCE_RESOURCE_PARENT = XACML2.ID_RESOURCE_RESOURCE_PARENT;
    this.ID_RESOURCE_RESOURCE_ANCESTOR = XACML2.ID_RESOURCE_RESOURCE_ANCESTOR;
    this.ID_RESOURCE_RESOURCE_ANCESTOR_OR_SELF = XACML2.ID_RESOURCE_RESOURCE_ANCESTOR_OR_SELF;

    /*
     * XACML v3.0 Multiple Decision Profile Version 1.0
     */
    this.ID_PROFILE_MULTIPLE = Utils.resolveURI(this.ID_PROFILE, "multiple");
    this.ID_PROFILE_MULTIPLE_SCOPE = Utils.resolveURI(this.ID_PROFILE_MULTIPLE, "scope");
    this.ID_PROFILE_MULTIPLE_XPATH_EXPRESSION = Utils.resolveURI(this.ID_PROFILE_MULTIPLE, "xpath-expression");
    this.ID_PROFILE_MULTIPLE_REPEATED_ATTRIBUTE_CATEGORIES = Utils.resolveURI(this.ID_PROFILE_MULTIPLE, "repeated-attribute-categories");
    this.ID_PROFILE_MULTIPLE_REFERENCE = Utils.resolveURI(this.ID_PROFILE_MULTIPLE, "reference");
    this.ID_PROFILE_MULTIPLE_COMBINED_DECISION = Utils.resolveURI(this.ID_PROFILE_MULTIPLE, "combined-decision");

    this.ID_MULTIPLE_CONTENT_SELECTOR = Utils.resolveURI(this.ID_XACML, "multiple:content-selector");
    this.ID_RESOURCE_SCOPE = XACML2.ID_RESOURCE_SCOPE;

    /*
     * XACML v3.0 Core and Hierarchical Role Based Access Control (RBAC) Profile Version 1.0
     */
    this.ID_PROFILES_RBAC_CORE_HIERARCHICAL = Utils.resolveURI(this.ID_PROFILES, "rback:core-hierarchical");
    this.ID_SUBJECT_ROLE = XACML2.ID_SUBJECT_ROLE;
    this.ID_SUBJECT_CATEGORY_ROLE_ENABLEMENT_AUTHORITY = XACML2.ID_SUBJECT_CATEGORY_ROLE_ENABLEMENT_AUTHORITY;
    this.ID_ACTIONS_HASPRIVILEGESOFROLE = XACML2.ID_ACTIONS_HASPRIVILEGESFROLE;
    this.ID_ACTIONS_ENABLEROLE = XACML2.ID_ACTIONS_ENABLEROLE;

    /*
     * XACML v3.0 Privacy Policy Profile Version 1.0
     */
    this.ID_RESOURCE_PURPOSE = XACML2.ID_RESOURCE_PURPOSE;
    this.ID_ACTION_PURPOSE = XACML2.ID_ACTION_PURPOSE;

    /*
     * XACML v3.0 XML Digital Signature Profile Version 1.0
     */

    /*
     * XACML Intellectual Property Control (IPC) Profile Version 1.0
     */
    this.ID_IPC = Utils.resolveURI(this.ID_XACML, "ipc");
    this.ID_IPC_RESOURCE = Utils.resolveURI(this.ID_IPC, XACML.RESOURCE);
    this.ID_IPC_RESOURCE_COPYRIGHT = Utils.resolveURI(this.ID_IPC_RESOURCE, "copyright");
    this.ID_IPC_RESOURCE_PATENT = Utils.resolveURI(this.ID_IPC_RESOURCE, "patent");
    this.ID_IPC_RESOURCE_PROPRIETARY = Utils.resolveURI(this.ID_IPC_RESOURCE, "proprietary");
    this.ID_IPC_RESOURCE_PUBLIC_DOMAIN = Utils.resolveURI(this.ID_IPC_RESOURCE, "public-domain");
    this.ID_IPC_RESOURCE_TRADEMARK = Utils.resolveURI(this.ID_IPC_RESOURCE, "trademark");
    this.ID_IPC_RESOURCE_IP_OWNER = Utils.resolveURI(this.ID_IPC_RESOURCE, "ip-owner");
    this.ID_IPC_RESOURCE_IP_LICENSEE = Utils.resolveURI(this.ID_IPC_RESOURCE, "ip-licensee");
    this.ID_IPC_RESOURCE_AGREEMENT_TYPE = Utils.resolveURI(this.ID_IPC_RESOURCE, "agreement-type");
    this.ID_IPC_RESOURCE_AGREEMENT_ID = Utils.resolveURI(this.ID_IPC_RESOURCE, "agreement-id");
    this.ID_IPC_RESOURCE_VALID_AGREEMENT_EXISTS = Utils.resolveURI(this.ID_IPC_RESOURCE, "valid-agreement-exists");
    this.ID_IPC_RESOURCE_NUMBER_OF_VALID_AGREEMENTS = Utils.resolveURI(this.ID_IPC_RESOURCE, "number-of-valid-agreements");
    this.ID_IPC_RESOURCE_WORK_EFFORT = Utils.resolveURI(this.ID_IPC_RESOURCE, "work-effort");
    this.ID_IPC_RESOURCE_AUTHORIZED_END_USE = Utils.resolveURI(this.ID_IPC_RESOURCE, "authorized-end-use");
    this.ID_IPC_RESOURCE_AUTHORIZED_END_USE_DESIGN = Utils.resolveURI(this.ID_IPC_RESOURCE_AUTHORIZED_END_USE, "design");
    this.ID_IPC_RESOURCE_AUTHORIZED_END_USE_MANUFACTURE = Utils.resolveURI(this.ID_IPC_RESOURCE_AUTHORIZED_END_USE, "manufacture");
    this.ID_IPC_RESOURCE_AUTHORIZED_END_USE_MAINTENANCE = Utils.resolveURI(this.ID_IPC_RESOURCE_AUTHORIZED_END_USE, "maintenance");
    this.ID_IPC_RESOURCE_EFFECTIVE_DATE = Utils.resolveURI(this.ID_IPC_RESOURCE, "effective-date");
    this.ID_IPC_RESOURCE_EXPIRATION_DATE = Utils.resolveURI(this.ID_IPC_RESOURCE, "expiration-date");
    this.ID_IPC_SUBJECT = Utils.resolveURI(this.ID_IPC, XACML.SUBJECT);
    this.ID_IPC_SUBJECT_SUBJECT_ID = Utils.resolveURI(this.ID_IPC_SUBJECT, "subject-id");
    this.ID_IPC_SUBJECT_ORGANIZATION = Utils.resolveURI(this.ID_IPC_SUBJECT, "organization");
    this.ID_IPC_SUBJECT_BUSINESS_CONTEXT = Utils.resolveURI(this.ID_IPC_SUBJECT, "business-context");
    this.ID_IPC_SUBJECT_BUSINESS_CONTEXT_CUSTOMER = Utils.resolveURI(this.ID_IPC_SUBJECT_BUSINESS_CONTEXT, "customer");
    this.ID_IPC_SUBJECT_BUSINESS_CONTEXT_SUPPLIER = Utils.resolveURI(this.ID_IPC_SUBJECT_BUSINESS_CONTEXT, "suppler");
    this.ID_IPC_SUBJECT_BUSINESS_CONTEXT_PARTNER = Utils.resolveURI(this.ID_IPC_SUBJECT_BUSINESS_CONTEXT, "partner");
    this.ID_IPC_SUBJECT_BUSINESS_CONTEXT_PRIMARY_CONTRACTOR = Utils.resolveURI(this.ID_IPC_SUBJECT_BUSINESS_CONTEXT, "primary-contractor");
    this.ID_IPC_SUBJECT_BUSINESS_CONTEXT_SUBCONTRACTOR = Utils.resolveURI(this.ID_IPC_SUBJECT_BUSINESS_CONTEXT, "subcontractor");
    this.ID_IPC_SUBJECT_BUSINESS_CONTEXT_AUTHORIZED_SUBLICENSOR = Utils.resolveURI(this.ID_IPC_SUBJECT_BUSINESS_CONTEXT, "authorized-sublicensor");
    this.ID_IPC_SUBJECT_SUBJECT_TO_ORGANIZATION_RELATIONSHIP = Utils.resolveURI(this.ID_IPC_SUBJECT, "subject-to-organization-relationship");
    this.ID_IPC_SUBJECT_SUBJECT_TO_ORGANIZATION_RELATIONSHIP_EMPLOYEE = Utils.resolveURI(this.ID_IPC_SUBJECT_SUBJECT_TO_ORGANIZATION_RELATIONSHIP, "employee");
    this.ID_IPC_SUBJECT_SUBJECT_TO_ORGANIZATION_RELATIONSHIP_CONTRACTOR = Utils.resolveURI(this.ID_IPC_SUBJECT_SUBJECT_TO_ORGANIZATION_RELATIONSHIP, "contractor");
    this.ID_IPC_SUBJECT_AGREEMENT_ID = Utils.resolveURI(this.ID_IPC_SUBJECT, "agreement-id");
    this.ID_IPC_OBLIGATION = Utils.resolveURI(this.ID_IPC, "obligation");
    this.ID_IPC_OBLIGATION_ENCRYPT = Utils.resolveURI(this.ID_IPC_OBLIGATION, "encrypt");
    this.ID_IPC_OBLIGATION_MARKING = Utils.resolveURI(this.ID_IPC_OBLIGATION, "marking");

    /*
     * XACML 3.0 Export Compliance-US (EC-US) Profile Version 1.0
     */
    this.ID_PROFILES_EC_US = Utils.resolveURI(this.ID_PROFILES, "ec-us");
    this.ID_EC_US = Utils.resolveURI(this.ID_XACML, "ec-us");
    this.ID_EC_US_RESOURCE = Utils.resolveURI(this.ID_EC_US, XACML.RESOURCE);
    this.ID_EC_US_RESOURCE_JURISDICTION = Utils.resolveURI(this.ID_EC_US_RESOURCE, "jurisdiction");
    this.ID_EC_US_RESOURCE_ECCN = Utils.resolveURI(this.ID_EC_US_RESOURCE, "eccn");
    this.ID_EC_US_RESOURCE_USML = Utils.resolveURI(this.ID_EC_US_RESOURCE, "usml");
    this.ID_EC_US_RESOURCE_AUTHORITY_TO_EXPORT = Utils.resolveURI(this.ID_EC_US_RESOURCE, "authority-to-export");
    this.ID_EC_US_RESOURCE_EFFECTIVE_DATE = Utils.resolveURI(this.ID_EC_US_RESOURCE, "effective-date");
    this.ID_EC_US_RESOURCE_EXPIRATION_DATE = Utils.resolveURI(this.ID_EC_US_RESOURCE, "expiration-date");
    this.ID_EC_US_SUBJECT = Utils.resolveURI(this.ID_EC_US, XACML.SUBJECT);
    this.ID_EC_US_SUBJECT_NATIONALITY = Utils.resolveURI(this.ID_EC_US_SUBJECT, "nationality");
    this.ID_EC_US_SUBJECT_CURRENT_NATIONALITY = Utils.resolveURI(this.ID_EC_US_SUBJECT, "current-nationality");
    this.ID_EC_US_SUBJECT_ORGANIZATION = Utils.resolveURI(this.ID_EC_US_SUBJECT, "organization");
    this.ID_EC_US_SUBJECT_US_PERSON = Utils.resolveURI(this.ID_EC_US_SUBJECT, "us-person");

    /*
     * REST Profile of XACML v3.0 Version 1.0
     */
    this.ID_PROFILE_REST = Utils.resolveURI(this.ID_PROFILE, "rest");
    this.ID_PROFILE_REST_HTTP = Utils.resolveURI(this.ID_PROFILE_REST, "http");
    this.ID_PROFILE_REST_HOME = Utils.resolveURI(this.ID_PROFILE_REST, "home");
    this.ID_PROFILE_REST_PDP = Utils.resolveURI(this.ID_PROFILE_REST, "pdp");

    /*
     * Request/Response Interface based on JSON and HTTP for XACML 3.0 Version 1.0
     */

    /*
     * XACML 3.0 Additional Combining Algorithms Profile Version 1.0
     */
    this.ID_POLICY_ON_PERMIT_APPLY_SECOND = Utils.resolveURI(this.ID_POLICY_COMBINING_ALGORITHM, "on-permit-apply-second");
});