"use strict";

var XACML = require("./XACML");
var XACML1 = require("./XACML1");
var Utils = require("../Utils");

module.exports = Object.freeze(new function() {
    /*
     * DOM Namespaces and schema
     */
    this.SCHEMA_LOCATION = "urn:oasis:names:tc:xacml:2.0:context:schema:os access_control-xacml-2.0-context-schema-os.xsd";
    this.XMLNS = "urn:oasis:names:tc:xacml:2.0:context:schema:os";
    this.XMLNS_XSI = "http://www.w3.org/2001/XMLSchema-instance";

    /*
     * URN builder components
     */
    this.VERSION_2_0 = "2.0";

    /*
     * 10.2.2 Identifier Prefixes
     */
    this.ID_XACML = Utils.resolveURI(XACML.ID_XACML, this.VERSION_2_0);
    this.ID_CONFORMANCE_TEST = Utils.resolveURI(this.ID_XACML, XACML.CONFORMANCE_TEST);
    this.ID_CONTEXT = Utils.resolveURI(this.ID_XACML, XACML.CONTEXT);
    this.ID_EXAMPLE = Utils.resolveURI(this.ID_XACML, XACML.EXAMPLE);
    this.ID_FUNCTION10 = XACML1.ID_FUNCTION;
    this.ID_FUNCTION = Utils.resolveURI(this.ID_XACML, XACML.FUNCTION);
    this.ID_POLICY = Utils.resolveURI(this.ID_XACML, XACML.POLICY);
    this.ID_SUBJECT = Utils.resolveURI(this.ID_XACML, XACML.SUBJECT);
    this.ID_SUBJECT_CATEGORY = Utils.resolveURI(this.ID_XACML, XACML.SUBJECT_CATEGORY);
    this.ID_RESOURCE = Utils.resolveURI(this.ID_XACML, XACML.RESOURCE);
    this.ID_ACTION = Utils.resolveURI(this.ID_XACML, XACML.ACTION);
    this.ID_ACTIONS = Utils.resolveURI(this.ID_XACML, XACML.ACTIONS);;
    this.ID_ENVIRONMENT = Utils.resolveURI(this.ID_XACML, XACML.ENVIRONMENT);
    this.ID_STATUS = XACML1.ID_STATUS;

    /*
     * 10.2.3 Algorithms
     */
    this.ID_RULE_DENY_OVERRIDES = XACML1.ID_RULE_DENY_OVERRIDES;
    this.ID_POLICY_DENY_OVERRIDES = XACML1.ID_POLICY_DENY_OVERRIDES;
    this.ID_RULE_PERMIT_OVERRIDES = XACML1.ID_RULE_PERMIT_OVERRIDES;
    this.ID_POLICY_PERMIT_OVERRIDES = XACML1.ID_POLICY_PERMIT_OVERRIDES;
    this.ID_RULE_FIRST_APPLICABLE = XACML1.ID_RULE_FIRST_APPLICABLE;
    this.ID_POLICY_FIRST_APPLICABLE = XACML1.ID_POLICY_FIRST_APPLICABLE;
    this.ID_RULE_ONLY_ONE_APPLICABLE = XACML1.ID_RULE_ONLY_ONE_APPLICABLE;
    this.ID_POLICY_ONLY_ONE_APPLICABLE = XACML1.ID_POLICY_ONLY_ONE_APPLICABLE;
    this.ID_RULE_ORDERED_DENY_OVERRIDES = XACML1.ID_RULE_ORDERED_DENY_OVERRIDES;
    this.ID_POLICY_ORDERED_DENY_OVERRIDES = XACML1.ID_POLICY_ORDERED_DENY_OVERRIDES;
    this.ID_RULE_ORDERED_PERMIT_OVERRIDES = XACML1.ID_RULE_ORDERED_PERMIT_OVERRIDES;
    this.ID_POLICY_ORDERED_PERMIT_OVERRIDES = XACML1.ID_POLICY_ORDERED_PERMIT_OVERRIDES;

    /*
     * 10.2.4 Status Codes
     */
    this.ID_STATUS_MISSING_ATTRIBUTE = XACML1.ID_STATUS_MISSING_ATTRIBUTE;
    this.ID_STATUS_OK = XACML1.ID_STATUS_OK;
    this.ID_STATUS_PROCESSING_ERROR = XACML1.ID_STATUS_PROCESSING_ERROR;
    this.ID_STATUS_SYNTAX_ERROR = XACML1.ID_STATUS_SYNTAX_ERROR;

    /*
     * Section 10.2.5 Attributes
     */
    this.ID_ENVIRONMENT_CURRENT_TIME = XACML1.ID_ENVIRONMENT_CURRENT_TIME;
    this.ID_ENVIRONMENT_CURRENT_DATE = XACML1.ID_ENVIRONMENT_CURRENT_DATE;
    this.ID_ENVIRONMENT_CURRENT_DATETIME = XACML1.ID_ENVIRONMENT_CURRENT_DATETIME;

    /*
     * Section 10.2.6 Identifiers
     */
    this.ID_SUBJECT_AUTHN_LOCALITY = XACML1.ID_SUBJECT_AUTHN_LOCALITY;
    this.ID_SUBJECT_AUTHN_LOCALITY_DNS_NAME = XACML1.ID_SUBJECT_AUTHN_LOCALITY_DNS_NAME;
    this.ID_SUBJECT_AUTHN_LOCALITY_IP_ADDRESS = XACML1.ID_SUBJECT_AUTHN_LOCALITY_IP_ADDRESS;
    this.ID_SUBJECT_AUTHENTICATION_METHOD = XACML1.ID_SUBJECT_AUTHENTICATION_METHOD;
    this.ID_SUBJECT_AUTHENTICATION_TIME = XACML1.ID_SUBJECT_AUTHENTICATION_TIME;
    this.ID_SUBJECT_KEY_INFO = XACML1.ID_SUBJECT_KEY_INFO;
    this.ID_SUBJECT_REQUEST_TIME = XACML1.ID_SUBJECT_REQUEST_TIME;
    this.ID_SUBJECT_SESSION_START_TIME = XACML1.ID_SUBJECT_SESSION_START_TIME;
    this.ID_SUBJECT_SUBJECT_ID = XACML1.ID_SUBJECT_SUBJECT_ID;
    this.ID_SUBJECT_SUBJECT_ID_QUALIFIER = XACML1.ID_SUBJECT_SUBJECT_ID_QUALIFIER;
    this.ID_SUBJECT_CATEGORY_ACCESS_SUBJECT = XACML1.ID_SUBJECT_CATEGORY_ACCESS_SUBJECT;
    this.ID_SUBJECT_CATEGORY_CODEBASE = XACML1.ID_SUBJECT_CATEGORY_CODEBASE;
    this.ID_SUBJECT_CATEGORY_INTERMEDIARY_SUBJECT = XACML1.ID_SUBJECT_CATEGORY_INTERMEDIARY_SUBJECT;
    this.ID_SUBJECT_CATEGORY_RECIPIENT_SUBJECT = XACML1.ID_SUBJECT_CATEGORY_RECIPIENT_SUBJECT;
    this.ID_SUBJECT_CATEGORY_REQUESTING_MACHINE = XACML1.ID_SUBJECT_CATEGORY_REQUESTING_MACHINE;
    this.ID_RESOURCE_RESOURCE_LOCATION = XACML1.ID_RESOURCE_RESOURCE_LOCATION;
    this.ID_RESOURCE_RESOURCE_ID = XACML1.ID_RESOURCE_RESOURCE_ID;
    this.ID_RESOURCE_TARGET_NAMESPACE = Utils.resolveURI(this.ID_RESOURCE, "target-namespace");
    this.ID_RESOURCE_SCOPE = Utils.resolveURI(this.ID_RESOURCE, "scope");
    this.ID_RESOURCE_SIMPLE_FILE_NAME = XACML1.ID_RESOURCE_SIMPLE_FILE_NAME;
    this.ID_ACTION_ACTION_ID = XACML1.ID_ACTION_ACTION_ID;
    this.ID_ACTION_IMPLIED_ACTION = XACML1.ID_ACTION_IMPLIED_ACTION;

    /*
     * Section 10.2.7 Data-types
     */
    this.ID_DATATYPE_STRING = XACML.ID_DATATYPE_STRING;
    this.ID_DATATYPE_BOOLEAN = XACML.ID_DATATYPE_BOOLEAN;
    this.ID_DATATYPE_INTEGER = XACML.ID_DATATYPE_BOOLEAN;
    this.ID_DATATYPE_DOUBLE = XACML.ID_DATATYPE_DOUBLE;
    this.ID_DATATYPE_TIME = XACML.ID_DATATYPE_TIME;
    this.ID_DATATYPE_DATE = XACML.ID_DATATYPE_DATE;
    this.ID_DATATYPE_DATETIME = XACML.ID_DATATYPE_DATETIME;
    this.ID_DATATYPE_DAYTIMEDURATION = XACML.ID_DATATYPE_WD_DAYTIMEDURATION;
    this.ID_DATATYPE_YEARMONTHDURATION = XACML.ID_DATATYPE_WD_YEARMONTHDURATION;
    this.ID_DATATYPE_ANYURI = XACML.ID_DATATYPE_ANYURI;
    this.ID_DATATYPE_HEXBINARY = XACML.ID_DATATYPE_HEXBINARY;
    this.ID_DATATYPE_BASE64BINARY = XACML.ID_DATATYPE_BASE64BINARY;
    this.ID_DATATYPE_RFC822NAME = XACML1.ID_DATATYPE_RFC822NAME;
    this.ID_DATATYPE_X500NAME = XACML1.ID_DATATYPE_X500NAME;

    this.ID_DATATYPE = Utils.resolveURI(this.ID_XACML, XACML.DATA_TYPE);
    this.ID_DATATYPE_IPADDRESS = Utils.resolveURI(this.ID_DATATYPE, "ipAddress");
    this.ID_DATATYPE_DNSNAME = Utils.resolveURI(this.ID_DATATYPE, "dnsName");

    /*
     * Section 10.2.8 Functions
     */

    this.ID_FUNCTION_STRING_EQUAL = XACML1.ID_FUNCTION_STRING_EQUAL;
    this.ID_FUNCTION_BOOLEAN_EQUAL = XACML1.ID_FUNCTION_BOOLEAN_EQUAL;
    this.ID_FUNCTION_INTEGER_EQUAL = XACML1.ID_FUNCTION_INTEGER_EQUAL;
    this.ID_FUNCTION_DOUBLE_EQUAL = XACML1.ID_FUNCTION_DOUBLE_EQUAL;
    this.ID_FUNCTION_DATE_EQUAL = XACML1.ID_FUNCTION_DATE_EQUAL;
    this.ID_FUNCTION_TIME_EQUAL = XACML1.ID_FUNCTION_TIME_EQUAL;
    this.ID_FUNCTION_DATETIME_EQUAL = XACML1.ID_FUNCTION_DATETIME_EQUAL;
    this.ID_FUNCTION_DAYTIMEDURATION_EQUAL = XACML1.ID_FUNCTION_DAYTIMEDURATION_EQUAL;
    this.ID_FUNCTION_YEARMONTHDURATION_EQUAL = XACML1.ID_FUNCTION_YEARMONTHDURATION_EQUAL;
    this.ID_FUNCTION_ANYURI_EQUAL = XACML1.ID_FUNCTION_ANYURI_EQUAL;
    this.ID_FUNCTION_X500NAME_EQUAL = XACML1.ID_FUNCTION_X500NAME_EQUAL;
    this.ID_FUNCTION_RFC822NAME_EQUAL = XACML1.ID_FUNCTION_RFC822NAME_EQUAL;
    this.ID_FUNCTION_HEXBINARY_EQUAL = XACML1.ID_FUNCTION_HEXBINARY_EQUAL;
    this.ID_FUNCTION_BASE64BINARY_EQUAL = XACML1.ID_FUNCTION_BASE64BINARY_EQUAL;
    this.ID_FUNCTION_INTEGER_ADD = XACML1.ID_FUNCTION_INTEGER_ADD;
    this.ID_FUNCTION_DOUBLE_ADD = XACML1.ID_FUNCTION_DOUBLE_ADD;
    this.ID_FUNCTION_INTEGER_SUBTRACT = XACML1.ID_FUNCTION_INTEGER_SUBTRACT;
    this.ID_FUNCTION_DOUBLE_SUBTRACT = XACML1.ID_FUNCTION_DOUBLE_SUBTRACT;
    this.ID_FUNCTION_INTEGER_MULTIPLY = XACML1.ID_FUNCTION_INTEGER_MULTIPLY;
    this.ID_FUNCTION_DOUBLE_MULTIPLY = XACML1.ID_FUNCTION_DOUBLE_MULTIPLY;
    this.ID_FUNCTION_INTEGER_DIVIDE = XACML1.ID_FUNCTION_INTEGER_DIVIDE;
    this.ID_FUNCTION_DOUBLE_DIVIDE = XACML1.ID_FUNCTION_DOUBLE_DIVIDE;
    this.ID_FUNCTION_INTEGER_MOD = XACML1.ID_FUNCTION_INTEGER_MOD;
    this.ID_FUNCTION_INTEGER_ABS = XACML1.ID_FUNCTION_INTEGER_ABS;
    this.ID_FUNCTION_DOUBLE_ABS = XACML1.ID_FUNCTION_DOUBLE_ABS;
    this.ID_FUNCTION_ROUND = XACML1.ID_FUNCTION_ROUND;
    this.ID_FUNCTION_FLOOR = XACML1.ID_FUNCTION_FLOOR;
    this.ID_FUNCTION_STRING_NORMALIZE_SPACE = XACML1.ID_FUNCTION_STRING_NORMALIZE_SPACE;
    this.ID_FUNCTION_STRING_NORMALIZE_TO_LOWER_CASE = XACML1.ID_FUNCTION_STRING_NORMALIZE_TO_LOWER_CASE;
    this.ID_FUNCTION_DOUBLE_TO_INTEGER = XACML1.ID_FUNCTION_DOUBLE_TO_INTEGER;
    this.ID_FUNCTION_INTEGER_TO_DOUBLE = XACML1.ID_FUNCTION_INTEGER_TO_DOUBLE;
    this.ID_FUNCTION_OR = XACML1.ID_FUNCTION_OR;
    this.ID_FUNCTION_AND = XACML1.ID_FUNCTION_AND;
    this.ID_FUNCTION_N_OF = XACML1.ID_FUNCTION_N_OF;
    this.ID_FUNCTION_NOT = XACML1.ID_FUNCTION_NOT;
    this.ID_FUNCTION_PRESENT = XACML1.ID_FUNCTION_PRESENT;
    this.ID_FUNCTION_INTEGER_GREATER_THAN = XACML1.ID_FUNCTION_INTEGER_GREATER_THAN;
    this.ID_FUNCTION_INTEGER_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_INTEGER_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_INTEGER_LESS_THAN = XACML1.ID_FUNCTION_INTEGER_LESS_THAN;
    this.ID_FUNCTION_INTEGER_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_INTEGER_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_DOUBLE_GREATER_THAN = XACML1.ID_FUNCTION_DOUBLE_GREATER_THAN;
    this.ID_FUNCTION_DOUBLE_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DOUBLE_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_DOUBLE_LESS_THAN = XACML1.ID_FUNCTION_DOUBLE_LESS_THAN;
    this.ID_FUNCTION_DOUBLE_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DOUBLE_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_DATETIME_ADD_DAYTIMEDURATION = XACML1.ID_FUNCTION_DATETIME_ADD_DAYTIMEDURATION;
    this.ID_FUNCTION_DATETIME_ADD_YEARMONTHDURATION = XACML1.ID_FUNCTION_DATETIME_ADD_YEARMONTHDURATION;
    this.ID_FUNCTION_DATETIME_SUBTRACT_DAYTIMEDURATION = XACML1.ID_FUNCTION_DATETIME_SUBTRACT_DAYTIMEDURATION;
    this.ID_FUNCTION_DATETIME_SUBTRACT_YEARMONTHDURATION = XACML1.ID_FUNCTION_DATETIME_SUBTRACT_YEARMONTHDURATION;
    this.ID_FUNCTION_DATE_ADD_YEARMONTHDURATION = XACML1.ID_FUNCTION_DATE_ADD_YEARMONTHDURATION;
    this.ID_FUNCTION_DATE_SUBTRACT_YEARMONTHDURATION = XACML1.ID_FUNCTION_DATE_SUBTRACT_YEARMONTHDURATION;
    this.ID_FUNCTION_STRING_GREATER_THAN = XACML1.ID_FUNCTION_STRING_GREATER_THAN;
    this.ID_FUNCTION_STRING_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_STRING_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_STRING_LESS_THAN = XACML1.ID_FUNCTION_STRING_LESS_THAN;
    this.ID_FUNCTION_STRING_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_STRING_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_TIME_GREATER_THAN = XACML1.ID_FUNCTION_TIME_GREATER_THAN;
    this.ID_FUNCTION_TIME_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_TIME_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_TIME_LESS_THAN = XACML1.ID_FUNCTION_TIME_LESS_THAN;
    this.ID_FUNCTION_TIME_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_TIME_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_TIME_IN_RANGE = Utils.resolveURI(this.ID_FUNCTION, "time-in-range");
    this.ID_FUNCTION_DATETIME_GREATER_THAN = XACML1.ID_FUNCTION_DATETIME_GREATER_THAN;
    this.ID_FUNCTION_DATETIME_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DATETIME_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_DATETIME_LESS_THAN = XACML1.ID_FUNCTION_DATETIME_LESS_THAN;
    this.ID_FUNCTION_DATETIME_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DATETIME_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_DATE_GREATER_THAN = XACML1.ID_FUNCTION_DATE_GREATER_THAN;
    this.ID_FUNCTION_DATE_GREATER_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DATE_GREATER_THAN_OR_EQUAL;
    this.ID_FUNCTION_DATE_LESS_THAN = XACML1.ID_FUNCTION_DATE_LESS_THAN;
    this.ID_FUNCTION_DATE_LESS_THAN_OR_EQUAL = XACML1.ID_FUNCTION_DATE_LESS_THAN_OR_EQUAL;
    this.ID_FUNCTION_STRING_ONE_AND_ONLY = XACML1.ID_FUNCTION_STRING_ONE_AND_ONLY;
    this.ID_FUNCTION_STRING_BAG_SIZE = XACML1.ID_FUNCTION_STRING_BAG_SIZE;
    this.ID_FUNCTION_STRING_IS_IN = XACML1.ID_FUNCTION_STRING_IS_IN;
    this.ID_FUNCTION_STRING_BAG = XACML1.ID_FUNCTION_STRING_BAG;
    this.ID_FUNCTION_BOOLEAN_ONE_AND_ONLY = XACML1.ID_FUNCTION_BOOLEAN_ONE_AND_ONLY;
    this.ID_FUNCTION_BOOLEAN_BAG_SIZE = XACML1.ID_FUNCTION_BOOLEAN_BAG_SIZE;
    this.ID_FUNCTION_BOOLEAN_IS_IN = XACML1.ID_FUNCTION_BOOLEAN_IS_IN;
    this.ID_FUNCTION_BOOLEAN_BAG = XACML1.ID_FUNCTION_BOOLEAN_BAG;
    this.ID_FUNCTION_INTEGER_ONE_AND_ONLY = XACML1.ID_FUNCTION_INTEGER_ONE_AND_ONLY;
    this.ID_FUNCTION_INTEGER_BAG_SIZE = XACML1.ID_FUNCTION_INTEGER_BAG_SIZE;
    this.ID_FUNCTION_INTEGER_IS_IN = XACML1.ID_FUNCTION_INTEGER_IS_IN;
    this.ID_FUNCTION_INTEGER_BAG = XACML1.ID_FUNCTION_INTEGER_BAG;
    this.ID_FUNCTION_DOUBLE_ONE_AND_ONLY = XACML1.ID_FUNCTION_DOUBLE_ONE_AND_ONLY;
    this.ID_FUNCTION_DOUBLE_BAG_SIZE = XACML1.ID_FUNCTION_DOUBLE_BAG_SIZE;
    this.ID_FUNCTION_DOUBLE_IS_IN = XACML1.ID_FUNCTION_DOUBLE_IS_IN;
    this.ID_FUNCTION_DOUBLE_BAG = XACML1.ID_FUNCTION_DOUBLE_BAG;
    this.ID_FUNCTION_TIME_ONE_AND_ONLY = XACML1.ID_FUNCTION_TIME_ONE_AND_ONLY;
    this.ID_FUNCTION_TIME_BAG_SIZE = XACML1.ID_FUNCTION_TIME_BAG_SIZE;
    this.ID_FUNCTION_TIME_IS_IN = XACML1.ID_FUNCTION_TIME_IS_IN;
    this.ID_FUNCTION_TIME_BAG = XACML1.ID_FUNCTION_TIME_BAG;
    this.ID_FUNCTION_DATE_ONE_AND_ONLY = XACML1.ID_FUNCTION_DATE_ONE_AND_ONLY;
    this.ID_FUNCTION_DATE_BAG_SIZE = XACML1.ID_FUNCTION_DATE_BAG_SIZE;
    this.ID_FUNCTION_DATE_IS_IN = XACML1.ID_FUNCTION_DATE_IS_IN;
    this.ID_FUNCTION_DATE_BAG = XACML1.ID_FUNCTION_DATE_BAG;
    this.ID_FUNCTION_DATETIME_ONE_AND_ONLY = XACML1.ID_FUNCTION_DATETIME_ONE_AND_ONLY;
    this.ID_FUNCTION_DATETIME_BAG_SIZE = XACML1.ID_FUNCTION_DATETIME_BAG_SIZE;
    this.ID_FUNCTION_DATETIME_IS_IN = XACML1.ID_FUNCTION_DATETIME_IS_IN;
    this.ID_FUNCTION_DATETIME_BAG = XACML1.ID_FUNCTION_DATETIME_BAG;
    this.ID_FUNCTION_ANYURI_ONE_AND_ONLY = XACML1.ID_FUNCTION_ANYURI_ONE_AND_ONLY;
    this.ID_FUNCTION_ANYURI_BAG_SIZE = XACML1.ID_FUNCTION_ANYURI_BAG_SIZE;
    this.ID_FUNCTION_ANYURI_IS_IN = XACML1.ID_FUNCTION_ANYURI_IS_IN;
    this.ID_FUNCTION_ANYURI_BAG = XACML1.ID_FUNCTION_ANYURI_BAG;
    this.ID_FUNCTION_HEXBINARY_ONE_AND_ONLY = XACML1.ID_FUNCTION_HEXBINARY_ONE_AND_ONLY;
    this.ID_FUNCTION_HEXBINARY_BAG_SIZE = XACML1.ID_FUNCTION_HEXBINARY_BAG_SIZE;
    this.ID_FUNCTION_HEXBINARY_IS_IN = XACML1.ID_FUNCTION_HEXBINARY_IS_IN;
    this.ID_FUNCTION_HEXBINARY_BAG = XACML1.ID_FUNCTION_HEXBINARY_BAG;
    this.ID_FUNCTION_BASE64BINARY_ONE_AND_ONLY = XACML1.ID_FUNCTION_BASE64BINARY_ONE_AND_ONLY;
    this.ID_FUNCTION_BASE64BINARY_BAG_SIZE = XACML1.ID_FUNCTION_BASE64BINARY_BAG_SIZE;
    this.ID_FUNCTION_BASE64BINARY_IS_IN = XACML1.ID_FUNCTION_BASE64BINARY_IS_IN;
    this.ID_FUNCTION_BASE64BINARY_BAG = XACML1.ID_FUNCTION_BASE64BINARY_BAG;
    this.ID_FUNCTION_DAYTIMEDURATION_ONE_AND_ONLY = XACML1.ID_FUNCTION_DAYTIMEDURATION_ONE_AND_ONLY;
    this.ID_FUNCTION_DAYTIMEDURATION_BAG_SIZE = XACML1.ID_FUNCTION_DAYTIMEDURATION_BAG_SIZE;
    this.ID_FUNCTION_DAYTIMEDURATION_IS_IN = XACML1.ID_FUNCTION_DAYTIMEDURATION_IS_IN;
    this.ID_FUNCTION_DAYTIMEDURATION_BAG = XACML1.ID_FUNCTION_DAYTIMEDURATION_BAG;
    this.ID_FUNCTION_YEARMONTHDURATION_ONE_AND_ONLY = XACML1.ID_FUNCTION_YEARMONTHDURATION_ONE_AND_ONLY;
    this.ID_FUNCTION_YEARMONTHDURATION_BAG_SIZE = XACML1.ID_FUNCTION_YEARMONTHDURATION_BAG_SIZE;
    this.ID_FUNCTION_YEARMONTHDURATION_IS_IN = XACML1.ID_FUNCTION_YEARMONTHDURATION_IS_IN;
    this.ID_FUNCTION_YEARMONTHDURATION_BAG = XACML1.ID_FUNCTION_YEARMONTHDURATION_BAG;
    this.ID_FUNCTION_X500NAME_ONE_AND_ONLY = XACML1.ID_FUNCTION_X500NAME_ONE_AND_ONLY;
    this.ID_FUNCTION_X500NAME_BAG_SIZE = XACML1.ID_FUNCTION_X500NAME_BAG_SIZE;
    this.ID_FUNCTION_X500NAME_IS_IN = XACML1.ID_FUNCTION_X500NAME_IS_IN;
    this.ID_FUNCTION_X500NAME_BAG = XACML1.ID_FUNCTION_X500NAME_BAG;
    this.ID_FUNCTION_RFC822NAME_ONE_AND_ONLY = XACML1.ID_FUNCTION_RFC822NAME_ONE_AND_ONLY;
    this.ID_FUNCTION_RFC822NAME_BAG_SIZE = XACML1.ID_FUNCTION_RFC822NAME_BAG_SIZE;
    this.ID_FUNCTION_RFC822NAME_IS_IN = XACML1.ID_FUNCTION_RFC822NAME_IS_IN;
    this.ID_FUNCTION_RFC822NAME_BAG = XACML1.ID_FUNCTION_RFC822NAME_BAG;
    this.ID_FUNCTION_IPADDRESS_ONE_AND_ONLY = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-one-and-only");
    this.ID_FUNCTION_IPADDRESS_BAG_SIZE = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-bag-size");
    this.ID_FUNCTION_IPADDRESS_IS_IN = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-is-in");
    this.ID_FUNCTION_IPADDRESS_BAG = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-bag");
    this.ID_FUNCTION_DNSNAME_ONE_AND_ONLY = Utils.resolveURI(this.ID_FUNCTION, "dnsName-one-and-only");
    this.ID_FUNCTION_DNSNAME_BAG_SIZE = Utils.resolveURI(this.ID_FUNCTION, "dnsName-bag-size");
    this.ID_FUNCTION_DNSNAME_IS_IN = Utils.resolveURI(this.ID_FUNCTION, "dnsName-is-in");
    this.ID_FUNCTION_DNSNAME_BAG = Utils.resolveURI(this.ID_FUNCTION, "dnsName-bag");
    this.ID_FUNCTION_STRING_CONCATENATE = Utils.resolveURI(this.ID_FUNCTION, "string-concatenate");
    this.ID_FUNCTION_STRING_URI_CONCATENATE = Utils.resolveURI(this.ID_FUNCTION, "string-uri-concatenate");
    this.ID_FUNCTION_ANY_OF = XACML1.ID_FUNCTION_ANY_OF;
    this.ID_FUNCTION_ALL_OF = XACML1.ID_FUNCTION_ALL_OF;
    this.ID_FUNCTION_ANY_OF_ANY = XACML1.ID_FUNCTION_ANY_OF_ANY;
    this.ID_FUNCTION_ALL_OF_ANY = XACML1.ID_FUNCTION_ALL_OF_ANY;
    this.ID_FUNCTION_ANY_OF_ALL = XACML1.ID_FUNCTION_ANY_OF_ALL;
    this.ID_FUNCTION_ALL_OF_ALL = XACML1.ID_FUNCTION_ALL_OF_ALL;
    this.ID_FUNCTION_MAP = XACML1.ID_FUNCTION_MAP;
    this.ID_FUNCTION_X500NAME_MATCH = XACML1.ID_FUNCTION_X500NAME_MATCH;
    this.ID_FUNCTION_RFC822NAME_MATCH = XACML1.ID_FUNCTION_RFC822NAME_MATCH;
    this.ID_FUNCTION_STRING_REGEXP_MATCH = XACML1.ID_FUNCTION_STRING_REGEXP_MATCH;
    this.ID_FUNCTION_ANYURI_REGEXP_MATCH = Utils.resolveURI(this.ID_FUNCTION, "anyURI-regexp-match");
    this.ID_FUNCTION_IPADDRESS_REGEXP_MATCH = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-regexp-match");
    this.ID_FUNCTION_DNSNAME_REGEXP_MATCH = Utils.resolveURI(this.ID_FUNCTION, "dnsName-regexp-match");
    this.ID_FUNCTION_RFC822NAME_REGEXP_MATCH = Utils.resolveURI(this.ID_FUNCTION, "rfc822Name-regexp-match");
    this.ID_FUNCTION_X500NAME_REGEXP_MATCH = Utils.resolveURI(this.ID_FUNCTION, "x500Name-regexp-match");
    // the following xpath-node functions are optional in 3.0 and are NOT included in this implementation. See
    // the Implementation Notes.
    // this.ID_FUNCTION_XPATH_NODE_COUNT = XACML1.ID_FUNCTION_XPATH_NODE_COUNT;
    // this.ID_FUNCTION_XPATH_NODE_EQUAL = XACML1.ID_FUNCTION_XPATH_NODE_EQUAL;
    // this.ID_FUNCTION_XPATH_NODE_MATCH = XACML1.ID_FUNCTION_XPATH_NODE_MATCH;
    this.ID_FUNCTION_STRING_INTERSECTION = XACML1.ID_FUNCTION_STRING_INTERSECTION;
    this.ID_FUNCTION_STRING_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_STRING_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_STRING_UNION = XACML1.ID_FUNCTION_STRING_UNION;
    this.ID_FUNCTION_STRING_SUBSET = XACML1.ID_FUNCTION_STRING_SUBSET;
    this.ID_FUNCTION_STRING_SET_EQUALS = XACML1.ID_FUNCTION_STRING_SET_EQUALS;
    this.ID_FUNCTION_BOOLEAN_INTERSECTION = XACML1.ID_FUNCTION_BOOLEAN_INTERSECTION;
    this.ID_FUNCTION_BOOLEAN_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_BOOLEAN_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_BOOLEAN_UNION = XACML1.ID_FUNCTION_BOOLEAN_UNION;
    this.ID_FUNCTION_BOOLEAN_SUBSET = XACML1.ID_FUNCTION_BOOLEAN_SUBSET;
    this.ID_FUNCTION_BOOLEAN_SET_EQUALS = XACML1.ID_FUNCTION_BOOLEAN_SET_EQUALS;
    this.ID_FUNCTION_INTEGER_INTERSECTION = XACML1.ID_FUNCTION_INTEGER_INTERSECTION;
    this.ID_FUNCTION_INTEGER_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_INTEGER_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_INTEGER_UNION = XACML1.ID_FUNCTION_INTEGER_UNION;
    this.ID_FUNCTION_INTEGER_SUBSET = XACML1.ID_FUNCTION_INTEGER_SUBSET;
    this.ID_FUNCTION_INTEGER_SET_EQUALS = XACML1.ID_FUNCTION_INTEGER_SET_EQUALS;
    this.ID_FUNCTION_DOUBLE_INTERSECTION = XACML1.ID_FUNCTION_DOUBLE_INTERSECTION;
    this.ID_FUNCTION_DOUBLE_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_DOUBLE_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_DOUBLE_UNION = XACML1.ID_FUNCTION_DOUBLE_UNION;
    this.ID_FUNCTION_DOUBLE_SUBSET = XACML1.ID_FUNCTION_DOUBLE_SUBSET;
    this.ID_FUNCTION_DOUBLE_SET_EQUALS = XACML1.ID_FUNCTION_DOUBLE_SET_EQUALS;
    this.ID_FUNCTION_TIME_INTERSECTION = XACML1.ID_FUNCTION_TIME_INTERSECTION;
    this.ID_FUNCTION_TIME_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_TIME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_TIME_UNION = XACML1.ID_FUNCTION_TIME_UNION;
    this.ID_FUNCTION_TIME_SUBSET = XACML1.ID_FUNCTION_TIME_SUBSET;
    this.ID_FUNCTION_TIME_SET_EQUALS = XACML1.ID_FUNCTION_TIME_SET_EQUALS;
    this.ID_FUNCTION_DATE_INTERSECTION = XACML1.ID_FUNCTION_DATE_INTERSECTION;
    this.ID_FUNCTION_DATE_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_DATE_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_DATE_UNION = XACML1.ID_FUNCTION_DATE_UNION;
    this.ID_FUNCTION_DATE_SUBSET = XACML1.ID_FUNCTION_DATE_SUBSET;
    this.ID_FUNCTION_DATE_SET_EQUALS = XACML1.ID_FUNCTION_DATE_SET_EQUALS;
    this.ID_FUNCTION_DATETIME_INTERSECTION = XACML1.ID_FUNCTION_DATETIME_INTERSECTION;
    this.ID_FUNCTION_DATETIME_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_DATETIME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_DATETIME_UNION = XACML1.ID_FUNCTION_DATETIME_UNION;
    this.ID_FUNCTION_DATETIME_SUBSET = XACML1.ID_FUNCTION_DATETIME_SUBSET;
    this.ID_FUNCTION_DATETIME_SET_EQUALS = XACML1.ID_FUNCTION_DATETIME_SET_EQUALS;
    this.ID_FUNCTION_ANYURI_INTERSECTION = XACML1.ID_FUNCTION_ANYURI_INTERSECTION;
    this.ID_FUNCTION_ANYURI_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_ANYURI_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_ANYURI_UNION = XACML1.ID_FUNCTION_ANYURI_UNION;
    this.ID_FUNCTION_ANYURI_SUBSET = XACML1.ID_FUNCTION_ANYURI_SUBSET;
    this.ID_FUNCTION_ANYURI_SET_EQUALS = XACML1.ID_FUNCTION_ANYURI_SET_EQUALS;
    this.ID_FUNCTION_HEXBINARY_INTERSECTION = XACML1.ID_FUNCTION_HEXBINARY_INTERSECTION;
    this.ID_FUNCTION_HEXBINARY_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_HEXBINARY_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_HEXBINARY_UNION = XACML1.ID_FUNCTION_HEXBINARY_UNION;
    this.ID_FUNCTION_HEXBINARY_SUBSET = XACML1.ID_FUNCTION_HEXBINARY_SUBSET;
    this.ID_FUNCTION_HEXBINARY_SET_EQUALS = XACML1.ID_FUNCTION_HEXBINARY_SET_EQUALS;
    this.ID_FUNCTION_BASE64BINARY_INTERSECTION = XACML1.ID_FUNCTION_BASE64BINARY_INTERSECTION;
    this.ID_FUNCTION_BASE64BINARY_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_BASE64BINARY_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_BASE64BINARY_UNION = XACML1.ID_FUNCTION_BASE64BINARY_UNION;
    this.ID_FUNCTION_BASE64BINARY_SUBSET = XACML1.ID_FUNCTION_BASE64BINARY_SUBSET;
    this.ID_FUNCTION_BASE64BINARY_SET_EQUALS = XACML1.ID_FUNCTION_BASE64BINARY_SET_EQUALS;
    this.ID_FUNCTION_DAYTIMEDURATION_INTERSECTION = XACML1.ID_FUNCTION_DAYTIMEDURATION_INTERSECTION;
    this.ID_FUNCTION_DAYTIMEDURATION_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_DAYTIMEDURATION_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_DAYTIMEDURATION_UNION = XACML1.ID_FUNCTION_DAYTIMEDURATION_UNION;
    this.ID_FUNCTION_DAYTIMEDURATION_SUBSET = XACML1.ID_FUNCTION_DAYTIMEDURATION_SUBSET;
    this.ID_FUNCTION_DAYTIMEDURATION_SET_EQUALS = XACML1.ID_FUNCTION_DAYTIMEDURATION_SET_EQUALS;
    this.ID_FUNCTION_YEARMONTHDURATION_INTERSECTION = XACML1.ID_FUNCTION_YEARMONTHDURATION_INTERSECTION;
    this.ID_FUNCTION_YEARMONTHDURATION_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_YEARMONTHDURATION_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_YEARMONTHDURATION_UNION = XACML1.ID_FUNCTION_YEARMONTHDURATION_UNION;
    this.ID_FUNCTION_YEARMONTHDURATION_SUBSET = XACML1.ID_FUNCTION_YEARMONTHDURATION_SUBSET;
    this.ID_FUNCTION_YEARMONTHDURATION_SET_EQUALS = XACML1.ID_FUNCTION_YEARMONTHDURATION_SET_EQUALS;
    this.ID_FUNCTION_X500NAME_INTERSECTION = XACML1.ID_FUNCTION_X500NAME_INTERSECTION;
    this.ID_FUNCTION_X500NAME_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_X500NAME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_X500NAME_UNION = XACML1.ID_FUNCTION_X500NAME_UNION;
    this.ID_FUNCTION_X500NAME_SUBSET = XACML1.ID_FUNCTION_X500NAME_SUBSET;
    this.ID_FUNCTION_X500NAME_SET_EQUALS = XACML1.ID_FUNCTION_X500NAME_SET_EQUALS;
    this.ID_FUNCTION_RFC822NAME_INTERSECTION = XACML1.ID_FUNCTION_RFC822NAME_INTERSECTION;
    this.ID_FUNCTION_RFC822NAME_AT_LEAST_ONE_MEMBER_OF = XACML1.ID_FUNCTION_RFC822NAME_AT_LEAST_ONE_MEMBER_OF;
    this.ID_FUNCTION_RFC822NAME_UNION = XACML1.ID_FUNCTION_RFC822NAME_UNION;
    this.ID_FUNCTION_RFC822NAME_SUBSET = XACML1.ID_FUNCTION_RFC822NAME_SUBSET;
    this.ID_FUNCTION_RFC822NAME_SET_EQUALS = XACML1.ID_FUNCTION_RFC822NAME_SET_EQUALS;
    this.ID_FUNCTION_IPADDRESS_INTERSECTION = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-intersection");
    this.ID_FUNCTION_IPADDRESS_AT_LEAST_ONE_MEMBER_OF = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-at-least-one-member-of");
    this.ID_FUNCTION_IPADDRESS_UNION = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-union");
    this.ID_FUNCTION_IPADDRESS_SUBSET = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-subset");
    this.ID_FUNCTION_IPADDRESS_SET_EQUALS = Utils.resolveURI(this.ID_FUNCTION, "ipAddress-set-equals");
    this.ID_FUNCTION_DNSNAME_INTERSECTION = Utils.resolveURI(this.ID_FUNCTION, "dnsName-intersection");
    this.ID_FUNCTION_DNSNAME_AT_LEAST_ONE_MEMBER_OF = Utils.resolveURI(this.ID_FUNCTION, "dnsName-at-least-one-member-of");
    this.ID_FUNCTION_DNSNAME_UNION = Utils.resolveURI(this.ID_FUNCTION, "dnsName-union");
    this.ID_FUNCTION_DNSNAME_SUBSET = Utils.resolveURI(this.ID_FUNCTION, "dnsName-subset");
    this.ID_FUNCTION_DNSNAME_SET_EQUALS = Utils.resolveURI(this.ID_FUNCTION, "dnsName-set-equals");

    // deprecated in 3.0
    this.ID_FUNCTION_URI_STRING_CONCATENATE = Utils.resolveURI(this.ID_FUNCTION, "uri-string-concatenate");

    /*
     * Profiles
     */
    this.ID_PROFILES = Utils.resolveURI(this.ID_XACML, XACML.PROFILES);
    this.ID_PROFILE = Utils.resolveURI(this.ID_XACML, XACML.PROFILE);

    /*
     * Core and hierarchical role based access control (RBAC) profile of XACML v2.0
     */
    this.ID_PROFILES_RBAC_CORE_HIERARCHICAL = Utils.resolveURI(this.ID_PROFILES, "rbac:core-hierarchical");
    this.ID_SUBJECT_ROLE = Utils.resolveURI(this.ID_SUBJECT, "role");
    this.ID_SUBJECT_CATEGORY_ROLE_ENABLEMENT_AUTHORITY = Utils.resolveURI(this.ID_SUBJECT_CATEGORY, "role-enablement-authority");
    this.ID_ACTIONS_HASPRIVILEGESFROLE = Utils.resolveURI(this.ID_ACTIONS, "hasPrivilegesOfRole");
    this.ID_ACTIONS_ENABLEROLE = Utils.resolveURI(this.ID_ACTIONS, "enableRole");

    /*
     * Hierarchical resource profile of XACML v2.0
     */
    this.ID_PROFILE_HIERARCHICAL = Utils.resolveURI(this.ID_PROFILE, "hierarchical");
    this.ID_PROFILE_HIERARCHICAL_XML_NODE_ID = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "xml-node-id");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_ID = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "non-xml-node-id");
    this.ID_PROFILE_HIERARCHICAL_XML_NODE_REQ = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "xml-node-req");
    this.ID_PROFILE_HIERARCHICAL_XML_NODE_REQ_RESOURCE_PARENT = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_XML_NODE_REQ, "resource-parent");
    this.ID_PROFILE_HIERARCHICAL_XML_NODE_REQ_RESOURCE_ANCESTOR = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_XML_NODE_REQ, "resource-ancestor");
    this.ID_PROFILE_HIERARCHICAL_XML_NODE_REQ_RESOURCE_ANCESTOR_OR_SELF = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_XML_NODE_REQ, "resource-ancestor-or-self");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL, "non-xml-node-req");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ_RESOURCE_PARENT = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ, "resource-parent");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ_RESOURCE_ANCESTOR = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ, "resource-ancestor");
    this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ_RESOURCE_ANCESTOR_OR_SELF = Utils.resolveURI(this.ID_PROFILE_HIERARCHICAL_NON_XML_NODE_REQ, "resource-ancestor-or-self");

    this.ID_RESOURCE_DOCUMENT_ID = Utils.resolveURI(this.ID_RESOURCE, "document-id");
    this.ID_RESOURCE_RESOURCE_PARENT = Utils.resolveURI(this.ID_RESOURCE, "resource-parent");
    this.ID_RESOURCE_RESOURCE_ANCESTOR = Utils.resolveURI(this.ID_RESOURCE, "resource-ancestor");
    this.ID_RESOURCE_RESOURCE_ANCESTOR_OR_SELF = Utils.resolveURI(this.ID_RESOURCE, "resource-ancestor-or-self");

    /*
     * Privacy ppolicy profile of XACML v2.0 TODO: No URI found
     */

    /*
     * SAML 2.0 profile of XACML v2.0
     */
    /*
     * SAML 2.0 Profile of XACML, Version 2.0
     */
    this.ID_PROFILE_SAML2_0_V2 = Utils.resolveURI(this.ID_PROFILE, "saml2.0:v2");
    this.ID_PROFILE_SAML2_0_V2_POLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "policies");
    this.ID_PROFILE_SAML2_0_V2_ADVICESAML = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "adviceSAML");
    this.ID_PROFILE_SAML2_0_V2_AUTHZTOKEN = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "authzToken");
    this.ID_PROFILE_SAML2_0_V2_ATTRS_ALL = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "attrs:all");
    this.ID_PROFILE_SAML2_0_V2_SOAP = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "SOAP");
    this.ID_PROFILE_SAML2_0_V2_SOAP_AUTHZQUERY = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_SOAP, "authzQuery");
    this.ID_PROFILE_SAML2_0_V2_SOAP_ATTRASSERTION = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_SOAP, "attrAssertion");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "authzDecision");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION_NOPOLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION, "noPolicies");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION_WITHPOLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_AUTHZDECISION, "withPolicies");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "authzDecisionWSTrust");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST_WITHPOLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST, "withPolicies");
    this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST_NOPOLICIES = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_AUTHZDECISIONWSTRUST, "noPolicies");
    this.ID_PROFILE_SAML2_0_V2_SCHEMA = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2, "schema");
    this.ID_PROFILE_SAML2_0_V2_SCHEMA_ASSERTION = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_SCHEMA, "assertion");
    this.ID_PROFILE_SAML2_0_V2_SCHEMA_PROTOCOL = Utils.resolveURI(this.ID_PROFILE_SAML2_0_V2_SCHEMA, "protocol");

    /*
     * XML Digital Signature profile of XACML v2.0 TODO: No URI found
     */

    /*
     * Cross-Enterprise Security and Privacy Authorization (SXPA) Profile of XACML v2.0 for Healthcare Version
     * 1.0 TODO: No URI found
     */

    /*
     * XACML v3.0 Privacy Policy Profile Version 1.0
     */
    this.ID_RESOURCE_PURPOSE = Utils.resolveURI(this.ID_RESOURCE, "purpose");
    this.ID_ACTION_PURPOSE = Utils.resolveURI(this.ID_ACTION, "purpose");
});